/*
 * PAP Submission — Terms & Conditions (Articles 1–12) in 9 languages.
 * Loaded by submission.html. Each value is the innerHTML of the <ol>
 * displayed inside #termsBox. setLang() swaps the content when the user
 * changes language. English remains the legal source of record; the
 * translations are provided for readability of non-English members.
 */
(function(){
  var T = {};

  // ─── Korean (ko) ──────────────────────────────────────────────────────
  T.ko = ''
  + '<li><strong>제1조 (작품의 독점 게재)</strong><br>'
  + '① 본 서브미션을 통해 제출된 에디토리얼(이하 "작품")은 PAP 매거진(이하 "PAP")에 독점 게재되며, 제출자는 동일한 작품을 타 매거진, 온라인 매체, 출판물 또는 이에 준하는 플랫폼에 게재·배포할 수 없습니다.<br>'
  + '② 본 조항을 위반하여 타 매체에 작품이 게재된 사실이 확인될 경우, PAP는 해당 작품을 즉시 삭제하고 향후 서브미션 제한 및 법적 조치 등 제출자에 대한 제재를 가할 수 있습니다.<br>'
  + '③ 독점 게재 기간은 PAP 웹사이트에 작품이 게시된 날로부터 무기한 적용됩니다.</li>'
  + '<li><strong>제2조 (웹사이트 및 소셜미디어 사용 동의)</strong><br>'
  + '① 제출된 작품은 PAP 공식 웹사이트(pap-magazine.com)에 게재되며, 게재 전후로 PAP 공식 소셜미디어 계정(인스타그램, 페이스북, 유튜브 등)에서 홍보 및 소개 목적으로 활용될 수 있습니다.<br>'
  + '② PAP는 홍보 목적으로 이미지의 크롭, 리사이즈, 필터 적용 등 합리적 범위의 편집을 수행할 수 있으나, 작품의 본질적 내용을 훼손하는 변경은 하지 않습니다.<br>'
  + '③ 모든 소셜미디어 게시물에는 제출자 및 팀원에 대한 정당한 크레딧이 표기됩니다.</li>'
  + '<li><strong>제3조 (크레딧 정보의 정확성 및 수정 수수료)</strong><br>'
  + '① 제출자는 모든 크레딧 정보(팀원 이름, 인스타그램 핸들, 브랜드명, 룩별 의상 크레딧 등)의 정확성과 최신성을 보증합니다.<br>'
  + '② 프리미엄 회원은 에디토리얼 1건당 3회까지 무료로 크레딧을 정정할 수 있습니다. 그 외의 경우, 게재 후 제출자의 책임에 의한 크레딧 수정에는 항목당 €100의 수정 수수료가 부과되며 수정 작업 시작 전 선납되어야 합니다.<br>'
  + '③ 서브미션 폼에 입력되지 않은 정보는 누락될 수 있으며, 이에 대해 PAP는 책임지지 않습니다.<br>'
  + '④ 크레딧 작성 시 전체 대문자(ALL CAPS) 사용은 금지됩니다.</li>'
  + '<li><strong>제4조 (콘텐츠 사용 권한 및 수익 분배)</strong><br>'
  + '① 제출된 작품이 PAP 디지털 매거진(웹사이트, 앱 등) 또는 인쇄물(종이 매거진, 출판물 등)에 게재되어 발생하는 모든 수익(구독료, 판매 수익, 광고 수익 등)은 전적으로 PAP에 귀속되며, 제출자 및 크리에이티브 팀은 매거진 게재로 인한 수익에 대해 별도의 보상을 청구할 수 없습니다.<br>'
  + '② 매거진 게재 범위를 벗어나는 2차 가공 또는 파생 상업 활동(광고 캠페인, 브랜드 협업, 라이선싱, 전시, 머천다이즈 등)에 작품이 활용되어 수익이 발생하는 경우, 해당 활동의 순이익(총수익에서 직접비용을 차감한 금액)은 PAP와 크리에이티브 팀이 50:50으로 분배합니다.<br>'
  + '③ 크리에이티브 팀에 배분된 수익은 제출자 또는 팀 대표자에게 일괄 지급되며, 팀 대표자가 팀원에게 수익을 배분하는 방식·비율·시점은 전적으로 팀 대표자의 재량이고 PAP는 팀 내부 수익 분배 과정에 관여하지 않으며 이에 대해 책임지지 않습니다.<br>'
  + '④ 2차 상업적 활용이 발생하는 경우, PAP는 사전에 서면(이메일 포함)으로 제출자에게 통지합니다.</li>'
  + '<li><strong>제5조 (저작권 및 지식재산권)</strong><br>'
  + '① 제출된 작품의 저작권은 원저작자에게 귀속됩니다. 다만 제출자는 본 약관에서 정한 범위 내에서 PAP에 독점적 사용권을 부여합니다.<br>'
  + '② 제출자는 제출된 모든 콘텐츠(사진, 영상, 텍스트 등)에 대한 정당한 권리를 보유하며, 해당 콘텐츠가 제3자의 저작권, 초상권, 상표권, 기타 지식재산권 또는 인격권을 침해하지 않음을 보증합니다.<br>'
  + '③ 제3자 권리 침해로 인해 PAP에 손해가 발생할 경우, 제출자는 이에 대한 모든 책임을 부담합니다.</li>'
  + '<li><strong>제6조 (게재 일정)</strong><br>'
  + '① 에디토리얼의 게재는 서브미션 승인일로부터 최대 2~3주가 소요될 수 있으며, 구체적인 게재 일정은 PAP 편집 일정에 따라 조정될 수 있습니다.</li>'
  + '<li><strong>제7조 (브랜드 포함 기준 및 브랜디드 콘텐츠)</strong><br>'
  + '① 에디토리얼은 최소 4개 이상의 서로 다른 의류 브랜드를 포함해야 합니다.<br>'
  + '② 단일 브랜드만 사용하거나 특정 브랜드 홍보를 주된 목적으로 하는 에디토리얼은 "브랜디드 콘텐츠"로 분류됩니다.<br>'
  + '③ 브랜디드 콘텐츠에는 별도의 게재 수수료가 부과되며, 구체적 금액은 PAP와 사전 협의를 통해 결정됩니다.<br>'
  + '④ 브랜드 포함 기준의 준수 여부는 PAP 에디토리얼 팀이 판단합니다.<br>'
  + '⑤ SPA(패스트패션) 브랜드와 빈티지·세컨핸드·리셀 매장에서 조달한 의상은 제1항의 브랜드 수에 포함되지 않습니다. 해당 여부는 PAP 편집팀이 판단합니다.</li>'
  + '<li><strong>제8조 (게재 후 수정 및 삭제)</strong><br>'
  + '① PAP 웹사이트 및 소셜미디어에 에디토리얼이 게재된 이후에는 원칙적으로 수정, 교체 또는 삭제가 허용되지 않습니다. 다만 크레딧 정보의 정정은 제3조에 따릅니다.<br>'
  + '② 다만 (a) 법적 분쟁 또는 법원의 명령, (b) 제3자 권리 침해가 확인된 경우, (c) 중대한 사실 오류가 발견된 경우 등 중대한 사유가 있는 경우 PAP와의 협의를 통해 처리할 수 있습니다.<br>'
  + '③ 위 사유로 인한 수정·삭제 요청에는 별도의 처리 수수료가 부과될 수 있습니다.</li>'
  + '<li><strong>제9조 (개인정보 수집 및 이용)</strong><br>'
  + '① PAP는 서브미션 접수, 심사, 게재, 크레딧 표기, 연락을 위하여 제출자 및 팀원의 개인정보(이름, 이메일 주소, 인스타그램 핸들, 웹사이트 URL 등)를 수집·이용합니다.<br>'
  + '② 수집된 개인정보는 위 목적 외 용도로 사용되지 않으며 PAP 개인정보처리방침에 따라 안전하게 관리됩니다.<br>'
  + '③ 제출자는 팀원의 개인정보를 제공하기 전에 해당 팀원의 동의를 받았음을 확인합니다.<br>'
  + '④ 개인정보 관련 문의는 contact@pap-magazine.com으로 연락해 주십시오.</li>'
  + '<li><strong>제10조 (면책 및 책임 제한)</strong><br>'
  + '① PAP는 서브미션 심사 결과에 대한 이의를 받지 않습니다. 심사 기준과 결과는 PAP 에디토리얼 팀의 전문적 판단에 따릅니다.<br>'
  + '② PAP는 천재지변, 시스템 장애, 네트워크 오류 등 불가항력적 사유로 인한 서비스 중단이나 데이터 손실에 대해 책임지지 않습니다.<br>'
  + '③ 본 약관 위반으로 발생한 모든 분쟁 및 손해에 대한 책임은 제출자에게 있습니다.</li>'
  + '<li><strong>제11조 (약관의 개정)</strong><br>'
  + '① PAP는 관련 법령의 변경이나 서비스 정책의 변경 등 합리적 사유가 있는 경우 본 약관을 개정할 수 있습니다.<br>'
  + '② 개정된 약관은 PAP 웹사이트 공지 후 7일이 경과한 시점부터 효력을 발생합니다.<br>'
  + '③ 제출자가 개정된 약관에 동의하지 않는 경우 서브미션을 중단할 수 있습니다.</li>'
  + '<li><strong>제12조 (준거법 및 관할)</strong><br>'
  + '① 본 약관의 해석 및 적용은 대한민국 법률에 따릅니다.<br>'
  + '② 본 약관과 관련하여 발생하는 모든 분쟁은 서울중앙지방법원을 제1심 전속 관할 법원으로 합니다.</li>';

  // ─── English (en) — legal source of record ────────────────────────────
  T.en = ''
  + '<li><strong>Article 1 (Exclusive Publication of Work)</strong><br>'
  + '① The editorial submitted through this submission process ("Work") will be published exclusively in PAP Magazine ("PAP"). Submitters may not publish or distribute the same Work on other magazines, online media, publications, or equivalent platforms.<br>'
  + '② If the Work is confirmed to have been published on other media in violation of this provision, PAP may immediately delete the Work and impose sanctions on the submitter, including restrictions on future submissions and legal action.<br>'
  + '③ The exclusive publication period applies indefinitely from the date the Work is posted on the PAP website.</li>'
  + '<li><strong>Article 2 (Website and Social Media Use Consent)</strong><br>'
  + '① The submitted Work will be published on PAP\'s official website (pap-magazine.com) and may be used for promotional and introductory purposes through PAP\'s official social media accounts (Instagram, Facebook, YouTube, etc.) before and after publication.<br>'
  + '② PAP may perform reasonable edits within appropriate scope — cropping, resizing, and applying filters to images for promotional purposes — without changes that compromise the essential content of the Work.<br>'
  + '③ Proper credit will be given to the submitter and team members on all social media posts.</li>'
  + '<li><strong>Article 3 (Accuracy of Credit Information and Correction Fee)</strong><br>'
  + '① The submitter warrants that all credit information (team member names, Instagram handles, brand names, look-by-look outfit credits, etc.) is accurate and up to date.<br>'
  + '② Premium members may correct credits free of charge up to 3 times per editorial. Otherwise, if credit information needs to be corrected after publication due to the submitter\'s responsibility, a correction fee of €100 per item will be charged and must be paid before the correction work begins.<br>'
  + '③ Information not entered in the submission form may be omitted, and PAP assumes no responsibility for this.<br>'
  + '④ Do not use all capitals (ALL CAPS) when writing credits.</li>'
  + '<li><strong>Article 4 (Content Usage Rights and Revenue Sharing)</strong><br>'
  + '① All revenue generated from publication of submitted Works in PAP\'s digital magazine (website, app, etc.) or print publications — including subscription fees, sales revenue, and advertising revenue — shall belong entirely to PAP. The submitter and creative team may not claim separate compensation for revenue arising from magazine publication.<br>'
  + '② If the Work is used for secondary processing or derivative commercial activities beyond magazine publication (advertising campaigns, brand collaborations, licensing, exhibitions, merchandising, etc.), the net profit (gross revenue minus direct costs) shall be split 50:50 between PAP and the creative team.<br>'
  + '③ The creative team\'s share shall be paid in a lump sum to the submitter or team representative. The manner, ratio, and timing of how the representative distributes such revenue among team members is entirely at the representative\'s discretion. PAP shall have no involvement in the team\'s internal revenue distribution and assumes no liability in this regard.<br>'
  + '④ PAP will provide prior written notice (including email) to the submitter before any secondary commercial use occurs.</li>'
  + '<li><strong>Article 5 (Copyright and Intellectual Property Rights)</strong><br>'
  + '① Copyright of the submitted Work remains with the original creator. However, the submitter grants PAP exclusive usage rights within the scope specified in these terms.<br>'
  + '② The submitter warrants that they hold legitimate rights to all submitted content (photos, videos, text, etc.) and that such content does not infringe third-party copyrights, portrait rights, trademarks, other intellectual property rights, or personal rights.<br>'
  + '③ The submitter assumes all liability for any damages to PAP resulting from third-party rights infringement.</li>'
  + '<li><strong>Article 6 (Publication Schedule)</strong><br>'
  + '① Publication of the editorial may take up to 2–3 weeks from the date of submission approval, and the specific schedule may be adjusted according to PAP\'s editorial calendar.</li>'
  + '<li><strong>Article 7 (Brand Inclusion Criteria and Branded Content)</strong><br>'
  + '① Editorials must include a minimum of 4 different clothing brands.<br>'
  + '② Editorials that use only a single brand or have the primary purpose of promoting a specific brand are classified as "Branded Content."<br>'
  + '③ Branded Content is subject to an additional publication fee, with the specific amount determined through prior consultation with PAP.<br>'
  + '④ Compliance with the brand inclusion criteria is determined by PAP\'s editorial team.<br>'
  + '⑤ Fast-fashion (SPA) labels and garments sourced from vintage, second-hand or resale stores are not counted toward the number of brands in paragraph ①. The PAP editorial team decides what qualifies.</li>'
  + '<li><strong>Article 8 (Modifications and Deletions After Publication)</strong><br>'
  + '① Once an editorial is published on the PAP website and social media, modifications, replacements, or deletions are generally not permitted. However, corrections to credit information are governed by Article 3.<br>'
  + '② Exceptions may be made through consultation with PAP only for: (a) legal disputes or court orders, (b) confirmed third-party rights infringement, or (c) critical factual errors.<br>'
  + '③ Requests for modifications or deletions for the above reasons may incur additional processing fees.</li>'
  + '<li><strong>Article 9 (Collection and Use of Personal Information)</strong><br>'
  + '① PAP collects and uses personal information (names, email addresses, Instagram handles, website URLs, etc.) of submitters and team members for the purposes of submission receipt, review, publication, credit attribution, and communication.<br>'
  + '② Collected personal information will not be used for purposes other than those stated above and will be safely managed in accordance with PAP\'s privacy policy.<br>'
  + '③ The submitter confirms that consent has been obtained from all team members whose personal information is submitted.<br>'
  + '④ For inquiries regarding personal information, please contact contact@pap-magazine.com.</li>'
  + '<li><strong>Article 10 (Disclaimer and Limitation of Liability)</strong><br>'
  + '① PAP does not accept appeals regarding submission review results. Review criteria and results are at the professional discretion of PAP\'s editorial team.<br>'
  + '② PAP is not liable for service interruptions or data loss due to force majeure events such as natural disasters, system failures, or network errors.<br>'
  + '③ The submitter is responsible for all disputes and damages arising from violations of these terms.</li>'
  + '<li><strong>Article 11 (Amendment of Terms)</strong><br>'
  + '① PAP may amend these terms if there are reasonable causes such as changes in relevant laws or service policies.<br>'
  + '② Amended terms take effect 7 days after notification on the PAP website.<br>'
  + '③ If the submitter does not agree to amended terms, they may discontinue submission.</li>'
  + '<li><strong>Article 12 (Governing Law and Jurisdiction)</strong><br>'
  + '① These terms shall be governed by and construed in accordance with the laws of the Republic of Korea.<br>'
  + '② The Seoul Central District Court shall have exclusive jurisdiction over any disputes arising from or related to these terms.</li>';

  // ─── German (de) ──────────────────────────────────────────────────────
  T.de = ''
  + '<li><strong>Artikel 1 (Exklusive Veröffentlichung des Werks)</strong><br>'
  + '① Das über dieses Submission-Verfahren eingereichte Editorial (das „Werk") wird exklusiv im PAP Magazine („PAP") veröffentlicht. Einreichende dürfen dasselbe Werk nicht in anderen Magazinen, Online-Medien, Publikationen oder vergleichbaren Plattformen veröffentlichen oder verbreiten.<br>'
  + '② Wird festgestellt, dass das Werk unter Verstoß gegen diese Bestimmung auf anderen Medien veröffentlicht wurde, kann PAP das Werk unverzüglich entfernen und Sanktionen wie Einreichungsbeschränkungen und rechtliche Schritte gegen die einreichende Person einleiten.<br>'
  + '③ Die Exklusivität gilt zeitlich unbegrenzt ab dem Tag der Veröffentlichung auf der PAP-Website.</li>'
  + '<li><strong>Artikel 2 (Einwilligung zur Nutzung auf Website und Social Media)</strong><br>'
  + '① Das eingereichte Werk wird auf der offiziellen PAP-Website (pap-magazine.com) veröffentlicht und kann vor und nach der Veröffentlichung über offizielle PAP-Social-Media-Konten (Instagram, Facebook, YouTube usw.) zu Werbe- und Einführungszwecken genutzt werden.<br>'
  + '② PAP kann im angemessenen Rahmen Bearbeitungen wie Zuschnitt, Größenänderung oder Filteranwendung für Werbezwecke vornehmen, ohne den wesentlichen Inhalt des Werks zu verändern.<br>'
  + '③ In allen Social-Media-Beiträgen werden die einreichende Person und Teammitglieder ordnungsgemäß als Credits aufgeführt.</li>'
  + '<li><strong>Artikel 3 (Genauigkeit der Credits und Korrekturgebühr)</strong><br>'
  + '① Die einreichende Person garantiert, dass alle Credit-Informationen (Namen der Teammitglieder, Instagram-Handles, Markennamen, Look-spezifische Outfit-Credits usw.) korrekt und aktuell sind.<br>'
  + '② Premium-Mitglieder können Credits bis zu dreimal je Editorial kostenfrei korrigieren. Andernfalls wird für Korrekturen, die nach der Veröffentlichung aus Verschulden der einreichenden Person erforderlich werden, eine Gebühr von 100 € je Position erhoben; diese ist vor Beginn der Korrektur zu entrichten.<br>'
  + '③ Nicht im Formular eingegebene Informationen können ausgelassen werden; PAP übernimmt hierfür keine Verantwortung.<br>'
  + '④ Credits dürfen nicht in GROSSBUCHSTABEN (ALL CAPS) verfasst werden.</li>'
  + '<li><strong>Artikel 4 (Nutzungsrechte und Einnahmenverteilung)</strong><br>'
  + '① Sämtliche Einnahmen aus der Veröffentlichung eingereichter Werke im digitalen PAP-Magazin (Website, App usw.) oder in Printpublikationen – einschließlich Abonnementgebühren, Verkaufserlösen und Werbeeinnahmen – stehen vollständig PAP zu. Einreichende und das Kreativteam können für Einnahmen aus der Magazinveröffentlichung keine gesonderte Vergütung beanspruchen.<br>'
  + '② Wird das Werk für Sekundärnutzungen oder abgeleitete kommerzielle Tätigkeiten außerhalb der Magazinveröffentlichung verwendet (Werbekampagnen, Markenkooperationen, Lizenzierungen, Ausstellungen, Merchandise usw.), wird der Nettogewinn (Bruttoeinnahmen abzüglich direkter Kosten) zu 50:50 zwischen PAP und dem Kreativteam aufgeteilt.<br>'
  + '③ Der Anteil des Kreativteams wird in einer Summe an die einreichende Person bzw. die Teamvertretung ausgezahlt. Art, Quote und Zeitpunkt der internen Verteilung liegen ausschließlich im Ermessen der Teamvertretung; PAP ist an der internen Verteilung nicht beteiligt und übernimmt hierfür keine Haftung.<br>'
  + '④ PAP informiert die einreichende Person im Voraus schriftlich (einschließlich E-Mail), bevor eine sekundäre kommerzielle Nutzung erfolgt.</li>'
  + '<li><strong>Artikel 5 (Urheber- und gewerbliche Schutzrechte)</strong><br>'
  + '① Das Urheberrecht am eingereichten Werk verbleibt bei der ursprünglichen Urheberin/dem ursprünglichen Urheber. Die einreichende Person räumt PAP jedoch im Rahmen dieser Bedingungen ein ausschließliches Nutzungsrecht ein.<br>'
  + '② Die einreichende Person garantiert, dass sie über die erforderlichen Rechte an allen eingereichten Inhalten (Fotos, Videos, Texten usw.) verfügt und dass diese keine Urheber-, Persönlichkeits-, Marken- oder sonstige Schutzrechte Dritter verletzen.<br>'
  + '③ Entstehen PAP Schäden durch Rechtsverletzungen Dritter, übernimmt die einreichende Person hierfür die volle Haftung.</li>'
  + '<li><strong>Artikel 6 (Veröffentlichungsplan)</strong><br>'
  + '① Die Veröffentlichung eines Editorials kann bis zu 2–3 Wochen ab Genehmigung der Einreichung dauern; der konkrete Zeitpunkt wird nach dem Redaktionsplan von PAP abgestimmt.</li>'
  + '<li><strong>Artikel 7 (Kriterien für Markennennung und Branded Content)</strong><br>'
  + '① Editorials müssen mindestens 4 unterschiedliche Modemarken enthalten.<br>'
  + '② Editorials mit nur einer Marke oder primär werblichem Charakter gelten als „Branded Content".<br>'
  + '③ Branded Content unterliegt einer zusätzlichen Veröffentlichungsgebühr, deren Höhe in Absprache mit PAP festgelegt wird.<br>'
  + '④ Die Einhaltung der Kriterien wird vom PAP-Redaktionsteam beurteilt.<br>'
  + '⑤ Fast-Fashion-Marken (SPA) sowie Kleidung aus Vintage-, Second-Hand- oder Resale-Läden zählen nicht zur Markenanzahl nach Absatz ①. Die Einordnung nimmt das PAP-Redaktionsteam vor.</li>'
  + '<li><strong>Artikel 8 (Änderungen und Löschungen nach Veröffentlichung)</strong><br>'
  + '① Nach der Veröffentlichung auf der PAP-Website und den Social-Media-Kanälen sind Änderungen, Austausch oder Löschungen grundsätzlich nicht zulässig. Korrekturen an den Credits richten sich jedoch nach Artikel 3.<br>'
  + '② Ausnahmen sind nach Absprache mit PAP nur zulässig bei: (a) Rechtsstreitigkeiten oder gerichtlichen Anordnungen, (b) nachgewiesener Verletzung von Rechten Dritter oder (c) gravierenden Sachfehlern.<br>'
  + '③ Für derartige Änderungs- oder Löschanfragen können zusätzliche Bearbeitungsgebühren anfallen.</li>'
  + '<li><strong>Artikel 9 (Erhebung und Nutzung personenbezogener Daten)</strong><br>'
  + '① PAP erhebt und nutzt personenbezogene Daten (Namen, E-Mail-Adressen, Instagram-Handles, Website-URLs usw.) von Einreichenden und Teammitgliedern zu Zwecken der Einreichungsbearbeitung, Prüfung, Veröffentlichung, Credit-Zuordnung und Kontaktaufnahme.<br>'
  + '② Die erhobenen Daten werden ausschließlich zu diesen Zwecken verwendet und gemäß der Datenschutzerklärung von PAP sicher verwaltet.<br>'
  + '③ Die einreichende Person bestätigt, dass vor der Übermittlung der Daten von Teammitgliedern deren Einwilligung eingeholt wurde.<br>'
  + '④ Anfragen zu personenbezogenen Daten richten Sie bitte an contact@pap-magazine.com.</li>'
  + '<li><strong>Artikel 10 (Haftungsausschluss und Haftungsbeschränkung)</strong><br>'
  + '① PAP akzeptiert keine Einsprüche gegen die Ergebnisse der Einreichungsprüfung. Prüfkriterien und Ergebnisse liegen im fachlichen Ermessen des PAP-Redaktionsteams.<br>'
  + '② PAP haftet nicht für Dienstunterbrechungen oder Datenverluste infolge höherer Gewalt, Systemausfällen oder Netzwerkfehlern.<br>'
  + '③ Für sämtliche Streitigkeiten und Schäden aus Verstößen gegen diese Bedingungen haftet die einreichende Person.</li>'
  + '<li><strong>Artikel 11 (Änderung der Bedingungen)</strong><br>'
  + '① PAP kann diese Bedingungen bei berechtigten Gründen (z. B. Änderungen der einschlägigen Gesetze oder Servicerichtlinien) anpassen.<br>'
  + '② Geänderte Bedingungen treten 7 Tage nach Bekanntgabe auf der PAP-Website in Kraft.<br>'
  + '③ Stimmt die einreichende Person den geänderten Bedingungen nicht zu, kann sie die Einreichung einstellen.</li>'
  + '<li><strong>Artikel 12 (Anwendbares Recht und Gerichtsstand)</strong><br>'
  + '① Diese Bedingungen unterliegen dem Recht der Republik Korea.<br>'
  + '② Ausschließlicher Gerichtsstand für alle Streitigkeiten aus oder im Zusammenhang mit diesen Bedingungen ist das Seoul Central District Court.</li>';

  // ─── Italian (it) ─────────────────────────────────────────────────────
  T.it = ''
  + '<li><strong>Articolo 1 (Pubblicazione Esclusiva dell\'Opera)</strong><br>'
  + '① L\'editoriale inviato tramite questo processo di submission (l\'"Opera") sarà pubblicato in esclusiva su PAP Magazine ("PAP"). Gli autori non possono pubblicare o distribuire la stessa Opera su altre riviste, media online, pubblicazioni o piattaforme equivalenti.<br>'
  + '② Qualora venga accertata la pubblicazione dell\'Opera su altri media in violazione di questa disposizione, PAP potrà eliminare immediatamente l\'Opera e imporre sanzioni all\'autore, tra cui restrizioni sulle submission future e azioni legali.<br>'
  + '③ L\'esclusiva si applica a tempo indeterminato dalla data di pubblicazione sul sito PAP.</li>'
  + '<li><strong>Articolo 2 (Consenso all\'Uso su Sito Web e Social Media)</strong><br>'
  + '① L\'Opera inviata sarà pubblicata sul sito ufficiale di PAP (pap-magazine.com) e potrà essere utilizzata a scopo promozionale e di presentazione sugli account social ufficiali di PAP (Instagram, Facebook, YouTube, ecc.) prima e dopo la pubblicazione.<br>'
  + '② PAP può effettuare modifiche ragionevoli — ritaglio, ridimensionamento e applicazione di filtri — a fini promozionali, senza alterare i contenuti essenziali dell\'Opera.<br>'
  + '③ In tutti i post sui social media saranno indicati i credit corretti per l\'autore e i membri del team.</li>'
  + '<li><strong>Articolo 3 (Accuratezza dei Credit e Tariffa di Correzione)</strong><br>'
  + '① L\'autore garantisce che tutte le informazioni sui credit (nomi dei membri del team, handle Instagram, nomi dei brand, credit look-by-look, ecc.) sono accurate e aggiornate.<br>'
  + '② I membri Premium possono correggere i credit gratuitamente fino a 3 volte per editoriale. Negli altri casi, se dopo la pubblicazione sono necessarie correzioni per responsabilità dell\'autore, sarà applicata una tariffa di €100 per voce, da saldare prima dell\'inizio del lavoro di correzione.<br>'
  + '③ Le informazioni non inserite nel form di submission potranno essere omesse; PAP non si assume responsabilità al riguardo.<br>'
  + '④ Non utilizzare il TUTTO MAIUSCOLO (ALL CAPS) nei credit.</li>'
  + '<li><strong>Articolo 4 (Diritti di Utilizzo dei Contenuti e Ripartizione dei Ricavi)</strong><br>'
  + '① Tutti i ricavi derivanti dalla pubblicazione delle Opere inviate nella rivista digitale PAP (sito web, app, ecc.) o nelle pubblicazioni cartacee — inclusi abbonamenti, vendite e pubblicità — appartengono interamente a PAP. L\'autore e il team creativo non possono rivendicare compensi separati per i ricavi derivanti dalla pubblicazione della rivista.<br>'
  + '② Se l\'Opera viene utilizzata per elaborazioni secondarie o attività commerciali derivate oltre la pubblicazione della rivista (campagne pubblicitarie, collaborazioni con brand, licensing, mostre, merchandising, ecc.), il profitto netto (ricavi lordi meno costi diretti) sarà ripartito al 50:50 tra PAP e il team creativo.<br>'
  + '③ La quota spettante al team creativo sarà corrisposta in un\'unica soluzione all\'autore o al rappresentante del team. Modalità, proporzioni e tempi di distribuzione interna sono a esclusiva discrezione del rappresentante; PAP non è coinvolta nella distribuzione interna e non si assume alcuna responsabilità al riguardo.<br>'
  + '④ PAP invierà all\'autore preavviso scritto (inclusa l\'email) prima di qualsiasi uso commerciale secondario.</li>'
  + '<li><strong>Articolo 5 (Diritti d\'Autore e Proprietà Intellettuale)</strong><br>'
  + '① Il diritto d\'autore sull\'Opera inviata resta al creatore originale. L\'autore concede tuttavia a PAP diritti d\'uso esclusivi nei limiti previsti dai presenti termini.<br>'
  + '② L\'autore garantisce di possedere i diritti legittimi su tutti i contenuti inviati (foto, video, testi, ecc.) e che tali contenuti non violano diritti d\'autore, diritti sull\'immagine, marchi, altri diritti di proprietà intellettuale o diritti della personalità di terzi.<br>'
  + '③ L\'autore assume ogni responsabilità per eventuali danni a PAP derivanti da violazione di diritti di terzi.</li>'
  + '<li><strong>Articolo 6 (Programma di Pubblicazione)</strong><br>'
  + '① La pubblicazione dell\'editoriale può richiedere fino a 2–3 settimane dalla data di approvazione della submission; il calendario specifico può essere adeguato al piano editoriale di PAP.</li>'
  + '<li><strong>Articolo 7 (Criteri di Inclusione Brand e Branded Content)</strong><br>'
  + '① Gli editoriali devono includere almeno 4 diversi brand di abbigliamento.<br>'
  + '② Gli editoriali che utilizzano un solo brand o hanno come scopo principale la promozione di un brand specifico sono classificati come "Branded Content".<br>'
  + '③ Il Branded Content è soggetto a una tariffa di pubblicazione aggiuntiva, il cui importo è definito tramite accordo preventivo con PAP.<br>'
  + '④ Il rispetto dei criteri di inclusione dei brand è determinato dal team editoriale di PAP.<br>'
  + '⑤ I marchi fast fashion (SPA) e i capi provenienti da negozi vintage, dell\'usato o di rivendita non rientrano nel numero di brand di cui al comma ①. La valutazione spetta al team editoriale di PAP.</li>'
  + '<li><strong>Articolo 8 (Modifiche e Rimozioni dopo la Pubblicazione)</strong><br>'
  + '① Una volta pubblicato l\'editoriale sul sito PAP e sui social media, modifiche, sostituzioni o rimozioni non sono in linea di principio consentite. Le correzioni dei credit sono tuttavia disciplinate dall\'Articolo 3.<br>'
  + '② Eccezioni sono ammesse, in accordo con PAP, solo per: (a) controversie legali o ordini del tribunale, (b) violazione accertata di diritti di terzi, (c) errori di fatto gravi.<br>'
  + '③ Le richieste di modifica o rimozione per i motivi sopra indicati possono comportare tariffe di lavorazione aggiuntive.</li>'
  + '<li><strong>Articolo 9 (Raccolta e Uso dei Dati Personali)</strong><br>'
  + '① PAP raccoglie e utilizza i dati personali (nomi, indirizzi email, handle Instagram, URL del sito, ecc.) di autori e membri del team per ricezione e revisione delle submission, pubblicazione, attribuzione dei credit e contatto.<br>'
  + '② I dati raccolti non saranno usati per finalità diverse da quelle indicate e saranno gestiti in sicurezza secondo l\'informativa privacy di PAP.<br>'
  + '③ L\'autore conferma di aver ottenuto il consenso dei membri del team prima di fornire i loro dati personali.<br>'
  + '④ Per richieste relative ai dati personali contattare contact@pap-magazine.com.</li>'
  + '<li><strong>Articolo 10 (Esonero di Responsabilità e Limitazione)</strong><br>'
  + '① PAP non accetta ricorsi sui risultati della valutazione delle submission. I criteri e gli esiti sono a discrezione professionale del team editoriale di PAP.<br>'
  + '② PAP non è responsabile per interruzioni del servizio o perdita di dati dovute a cause di forza maggiore, guasti di sistema o errori di rete.<br>'
  + '③ L\'autore è responsabile di tutte le controversie e i danni derivanti dalla violazione di questi termini.</li>'
  + '<li><strong>Articolo 11 (Modifica dei Termini)</strong><br>'
  + '① PAP può modificare questi termini in presenza di motivi ragionevoli, quali modifiche di leggi rilevanti o delle policy di servizio.<br>'
  + '② I termini modificati entrano in vigore 7 giorni dopo la notifica sul sito PAP.<br>'
  + '③ Se l\'autore non accetta i termini modificati, può interrompere la submission.</li>'
  + '<li><strong>Articolo 12 (Legge Applicabile e Foro Competente)</strong><br>'
  + '① Questi termini sono regolati dalle leggi della Repubblica di Corea.<br>'
  + '② Per qualsiasi controversia derivante da o relativa a questi termini è esclusivamente competente il Seoul Central District Court in primo grado.</li>';

  // ─── French (fr) ──────────────────────────────────────────────────────
  T.fr = ''
  + '<li><strong>Article 1 (Publication Exclusive de l\'Œuvre)</strong><br>'
  + '① L\'éditorial soumis via ce processus de submission (l\'« Œuvre ») sera publié en exclusivité dans PAP Magazine (« PAP »). Les auteurs ne peuvent publier ou distribuer la même Œuvre sur d\'autres magazines, médias en ligne, publications ou plateformes équivalentes.<br>'
  + '② Si la publication de l\'Œuvre sur d\'autres médias en violation de cette disposition est constatée, PAP peut immédiatement supprimer l\'Œuvre et imposer des sanctions à l\'auteur, y compris des restrictions sur les futures soumissions et des actions en justice.<br>'
  + '③ La période d\'exclusivité s\'applique indéfiniment à partir de la date de publication sur le site PAP.</li>'
  + '<li><strong>Article 2 (Consentement à l\'Utilisation sur le Site et les Réseaux Sociaux)</strong><br>'
  + '① L\'Œuvre soumise sera publiée sur le site officiel de PAP (pap-magazine.com) et pourra être utilisée à des fins promotionnelles sur les comptes de réseaux sociaux officiels de PAP (Instagram, Facebook, YouTube, etc.) avant et après la publication.<br>'
  + '② PAP peut effectuer des modifications raisonnables — recadrage, redimensionnement, filtres — à des fins promotionnelles, sans altérer le contenu essentiel de l\'Œuvre.<br>'
  + '③ Tous les posts sur les réseaux sociaux mentionneront les crédits appropriés pour l\'auteur et les membres de l\'équipe.</li>'
  + '<li><strong>Article 3 (Exactitude des Crédits et Frais de Correction)</strong><br>'
  + '① L\'auteur garantit que toutes les informations de crédit (noms des membres de l\'équipe, pseudos Instagram, noms de marques, crédits look par look, etc.) sont exactes et à jour.<br>'
  + '② Les membres Premium peuvent corriger les crédits gratuitement, jusqu\'à 3 fois par éditorial. Dans les autres cas, si des corrections des crédits sont nécessaires après publication du fait de l\'auteur, des frais de 100 € par élément seront facturés et devront être réglés avant le début du travail.<br>'
  + '③ Les informations non saisies dans le formulaire de submission peuvent être omises, et PAP décline toute responsabilité à ce titre.<br>'
  + '④ Ne pas utiliser TOUT EN MAJUSCULES (ALL CAPS) dans les crédits.</li>'
  + '<li><strong>Article 4 (Droits d\'Utilisation et Partage des Revenus)</strong><br>'
  + '① Tous les revenus générés par la publication des Œuvres soumises dans le magazine numérique de PAP (site web, application, etc.) ou les publications imprimées — abonnements, ventes, recettes publicitaires — reviennent intégralement à PAP. L\'auteur et l\'équipe créative ne peuvent réclamer de rémunération distincte pour ces revenus.<br>'
  + '② Si l\'Œuvre est utilisée pour un traitement secondaire ou des activités commerciales dérivées hors publication (campagnes publicitaires, collaborations de marques, licences, expositions, merchandising, etc.), le bénéfice net (revenus bruts moins coûts directs) sera partagé 50:50 entre PAP et l\'équipe créative.<br>'
  + '③ La part de l\'équipe sera versée en une somme forfaitaire à l\'auteur ou au représentant de l\'équipe. Les modalités, la proportion et le calendrier de répartition interne sont à la seule discrétion du représentant ; PAP n\'intervient pas dans la répartition interne et n\'assume aucune responsabilité à ce titre.<br>'
  + '④ PAP préviendra l\'auteur par écrit (y compris par e-mail) avant tout usage commercial secondaire.</li>'
  + '<li><strong>Article 5 (Droits d\'Auteur et Propriété Intellectuelle)</strong><br>'
  + '① Le droit d\'auteur sur l\'Œuvre soumise demeure au créateur original. L\'auteur accorde toutefois à PAP des droits d\'utilisation exclusifs dans le cadre des présents termes.<br>'
  + '② L\'auteur garantit détenir les droits légitimes sur tous les contenus soumis (photos, vidéos, textes, etc.) et que ceux-ci ne violent aucun droit d\'auteur, droit à l\'image, marque, propriété intellectuelle ou droit de la personnalité de tiers.<br>'
  + '③ L\'auteur assume toute responsabilité pour les dommages causés à PAP à la suite de la violation de droits de tiers.</li>'
  + '<li><strong>Article 6 (Calendrier de Publication)</strong><br>'
  + '① La publication de l\'éditorial peut prendre jusqu\'à 2–3 semaines à compter de l\'approbation de la submission ; le calendrier précis peut être ajusté selon le planning éditorial de PAP.</li>'
  + '<li><strong>Article 7 (Critères d\'Inclusion des Marques et Contenu Sponsorisé)</strong><br>'
  + '① Les éditoriaux doivent inclure au minimum 4 marques de vêtements différentes.<br>'
  + '② Les éditoriaux n\'utilisant qu\'une seule marque ou visant principalement la promotion d\'une marque sont classés comme « Branded Content ».<br>'
  + '③ Le Branded Content est soumis à des frais de publication supplémentaires, dont le montant est déterminé en concertation préalable avec PAP.<br>'
  + '④ Le respect des critères est apprécié par l\'équipe éditoriale de PAP.<br>'
  + '⑤ Les marques de fast fashion (SPA) et les vêtements provenant de boutiques vintage, de seconde main ou de revente ne comptent pas dans le nombre de marques du paragraphe ①. L\'équipe éditoriale de PAP en juge.</li>'
  + '<li><strong>Article 8 (Modifications et Suppressions après Publication)</strong><br>'
  + '① Une fois l\'éditorial publié sur le site et les réseaux sociaux de PAP, les modifications, remplacements ou suppressions ne sont en principe pas autorisés. Toutefois, les corrections des crédits relèvent de l\'Article 3.<br>'
  + '② Des exceptions peuvent être accordées, en concertation avec PAP, uniquement en cas de : (a) litige juridique ou décision de justice, (b) violation avérée de droits de tiers, (c) erreurs factuelles majeures.<br>'
  + '③ Les demandes de modification ou de suppression pour ces motifs peuvent entraîner des frais de traitement supplémentaires.</li>'
  + '<li><strong>Article 9 (Collecte et Utilisation des Données Personnelles)</strong><br>'
  + '① PAP collecte et utilise les données personnelles (noms, adresses e-mail, pseudos Instagram, URL de site, etc.) des auteurs et membres de l\'équipe pour la réception et l\'évaluation des submissions, la publication, l\'attribution des crédits et les communications.<br>'
  + '② Les données collectées ne seront pas utilisées à d\'autres fins et seront gérées en sécurité conformément à la politique de confidentialité de PAP.<br>'
  + '③ L\'auteur confirme avoir obtenu le consentement des membres de l\'équipe avant de fournir leurs données personnelles.<br>'
  + '④ Pour toute question sur les données personnelles, contactez contact@pap-magazine.com.</li>'
  + '<li><strong>Article 10 (Déclaration de Non-Responsabilité)</strong><br>'
  + '① PAP n\'accepte pas les recours concernant les résultats de l\'évaluation des submissions. Les critères et résultats relèvent du jugement professionnel de l\'équipe éditoriale de PAP.<br>'
  + '② PAP n\'est pas responsable des interruptions de service ou pertes de données dues à des cas de force majeure, pannes système ou erreurs réseau.<br>'
  + '③ L\'auteur est responsable de tous les litiges et dommages résultant de la violation des présents termes.</li>'
  + '<li><strong>Article 11 (Modification des Termes)</strong><br>'
  + '① PAP peut modifier les présents termes en cas de motifs raisonnables (évolution de la législation ou des politiques de service).<br>'
  + '② Les termes modifiés entrent en vigueur 7 jours après notification sur le site PAP.<br>'
  + '③ Si l\'auteur n\'accepte pas les termes modifiés, il peut cesser sa submission.</li>'
  + '<li><strong>Article 12 (Droit Applicable et Juridiction)</strong><br>'
  + '① Les présents termes sont régis par les lois de la République de Corée.<br>'
  + '② Le Tribunal de District Central de Séoul est seul compétent en première instance pour tout litige découlant des présents termes.</li>';

  // ─── Spanish (es) ─────────────────────────────────────────────────────
  T.es = ''
  + '<li><strong>Artículo 1 (Publicación Exclusiva de la Obra)</strong><br>'
  + '① El editorial enviado a través de este proceso de submission (la "Obra") se publicará en exclusiva en PAP Magazine ("PAP"). Los autores no podrán publicar ni distribuir la misma Obra en otras revistas, medios en línea, publicaciones o plataformas equivalentes.<br>'
  + '② Si se comprueba que la Obra ha sido publicada en otros medios en contravención de esta disposición, PAP podrá eliminar inmediatamente la Obra e imponer sanciones al autor, incluidas restricciones a futuras submissions y acciones legales.<br>'
  + '③ La exclusividad se aplica por tiempo indefinido desde la fecha de publicación en el sitio de PAP.</li>'
  + '<li><strong>Artículo 2 (Consentimiento de Uso en Web y Redes Sociales)</strong><br>'
  + '① La Obra se publicará en el sitio oficial de PAP (pap-magazine.com) y podrá usarse con fines promocionales en las cuentas oficiales de PAP (Instagram, Facebook, YouTube, etc.) antes y después de la publicación.<br>'
  + '② PAP podrá realizar ediciones razonables — recorte, redimensionado y filtros — con fines promocionales, sin alterar el contenido esencial de la Obra.<br>'
  + '③ Todas las publicaciones en redes sociales incluirán los créditos adecuados para el autor y el equipo.</li>'
  + '<li><strong>Artículo 3 (Exactitud de los Créditos y Tarifa de Corrección)</strong><br>'
  + '① El autor garantiza que toda la información de créditos (nombres del equipo, handles de Instagram, marcas, créditos look por look, etc.) es precisa y está actualizada.<br>'
  + '② Los miembros Premium pueden corregir los créditos de forma gratuita hasta 3 veces por editorial. En los demás casos, si tras la publicación se requieren correcciones por responsabilidad del autor, se cobrará una tarifa de 100 € por elemento, pagadera antes de iniciar la corrección.<br>'
  + '③ La información no introducida en el formulario podrá omitirse; PAP no asume responsabilidad al respecto.<br>'
  + '④ No escriba los créditos TODO EN MAYÚSCULAS (ALL CAPS).</li>'
  + '<li><strong>Artículo 4 (Derechos de Uso y Reparto de Ingresos)</strong><br>'
  + '① Todos los ingresos derivados de la publicación de las Obras en la revista digital de PAP (web, app, etc.) o en publicaciones impresas — suscripciones, ventas, publicidad — pertenecen íntegramente a PAP. El autor y el equipo creativo no pueden reclamar compensación separada por esos ingresos.<br>'
  + '② Si la Obra se usa en procesamientos secundarios o actividades comerciales derivadas más allá de la publicación (campañas publicitarias, colaboraciones de marca, licencias, exposiciones, merchandising, etc.), el beneficio neto (ingresos brutos menos costes directos) se repartirá 50:50 entre PAP y el equipo creativo.<br>'
  + '③ La parte correspondiente al equipo se abonará en un pago único al autor o al representante del equipo. La forma, proporción y plazos de distribución interna son a criterio exclusivo del representante; PAP no interviene ni asume responsabilidad al respecto.<br>'
  + '④ PAP notificará por escrito (incluido email) al autor antes de cualquier uso comercial secundario.</li>'
  + '<li><strong>Artículo 5 (Derechos de Autor y Propiedad Intelectual)</strong><br>'
  + '① Los derechos de autor de la Obra permanecen en el creador original. El autor concede a PAP derechos exclusivos de uso en el ámbito definido en estos términos.<br>'
  + '② El autor garantiza poseer los derechos legítimos sobre todo el contenido enviado (fotos, vídeos, textos, etc.) y que dicho contenido no infringe derechos de autor, de imagen, marcas u otros derechos de propiedad intelectual o de la personalidad de terceros.<br>'
  + '③ El autor asume toda responsabilidad por los daños a PAP derivados de la infracción de derechos de terceros.</li>'
  + '<li><strong>Artículo 6 (Calendario de Publicación)</strong><br>'
  + '① La publicación del editorial puede tardar hasta 2–3 semanas desde la aprobación de la submission; el calendario concreto puede ajustarse según la agenda editorial de PAP.</li>'
  + '<li><strong>Artículo 7 (Criterios de Inclusión de Marcas y Branded Content)</strong><br>'
  + '① Los editoriales deben incluir al menos 4 marcas de moda distintas.<br>'
  + '② Los editoriales que usen una sola marca o cuyo objetivo principal sea la promoción de una marca se clasifican como "Branded Content".<br>'
  + '③ El Branded Content conlleva una tarifa de publicación adicional, determinada mediante consulta previa con PAP.<br>'
  + '④ El cumplimiento del criterio lo decide el equipo editorial de PAP.<br>'
  + '⑤ Las marcas de moda rápida (SPA) y las prendas procedentes de tiendas vintage, de segunda mano o de reventa no cuentan para el número de marcas del apartado ①. El equipo editorial de PAP determina qué aplica.</li>'
  + '<li><strong>Artículo 8 (Modificaciones y Eliminaciones tras la Publicación)</strong><br>'
  + '① Una vez publicado el editorial en la web y redes sociales de PAP, en principio no se permiten modificaciones, sustituciones ni eliminaciones. No obstante, las correcciones de los créditos se rigen por el Artículo 3.<br>'
  + '② Las excepciones se tramitarán con PAP únicamente por: (a) disputas legales u órdenes judiciales, (b) infracción confirmada de derechos de terceros, o (c) errores de hecho graves.<br>'
  + '③ Las solicitudes de modificación o eliminación por esos motivos pueden generar tarifas adicionales.</li>'
  + '<li><strong>Artículo 9 (Recopilación y Uso de Datos Personales)</strong><br>'
  + '① PAP recopila y usa datos personales (nombres, correos, handles de Instagram, URLs, etc.) de autores y miembros del equipo para la recepción y revisión de submissions, publicación, atribución de créditos y contacto.<br>'
  + '② Los datos se gestionan con seguridad conforme a la política de privacidad de PAP y no se usarán para otros fines.<br>'
  + '③ El autor confirma haber obtenido el consentimiento de los miembros del equipo antes de facilitar sus datos.<br>'
  + '④ Consultas sobre datos personales: contact@pap-magazine.com.</li>'
  + '<li><strong>Artículo 10 (Exención de Responsabilidad)</strong><br>'
  + '① PAP no admite recursos sobre los resultados de la revisión de submissions. Los criterios y resultados son competencia del equipo editorial de PAP.<br>'
  + '② PAP no es responsable de interrupciones del servicio o pérdida de datos por fuerza mayor, fallos del sistema o errores de red.<br>'
  + '③ El autor es responsable de todas las disputas y daños derivados de violaciones de estos términos.</li>'
  + '<li><strong>Artículo 11 (Modificación de los Términos)</strong><br>'
  + '① PAP puede modificar estos términos por motivos razonables, como cambios en la legislación o en las políticas del servicio.<br>'
  + '② Los términos modificados entran en vigor 7 días después de su notificación en el sitio de PAP.<br>'
  + '③ Si el autor no acepta los términos modificados, puede interrumpir su submission.</li>'
  + '<li><strong>Artículo 12 (Ley Aplicable y Jurisdicción)</strong><br>'
  + '① Estos términos se rigen por las leyes de la República de Corea.<br>'
  + '② El Tribunal del Distrito Central de Seúl tendrá jurisdicción exclusiva como tribunal de primera instancia sobre cualquier disputa derivada de estos términos.</li>';

  // ─── Japanese (ja) ────────────────────────────────────────────────────
  T.ja = ''
  + '<li><strong>第1条(作品の独占掲載)</strong><br>'
  + '① 本サブミッションを通じて提出されたエディトリアル(以下「作品」)はPAP Magazine(以下「PAP」)に独占的に掲載され、提出者は同一の作品を他の雑誌、オンラインメディア、出版物、またはこれに準ずるプラットフォームに掲載・配布することはできません。<br>'
  + '② 本条項に違反して作品が他のメディアに掲載されたことが確認された場合、PAPは直ちに作品を削除し、今後のサブミッション制限や法的措置を含む制裁を科すことがあります。<br>'
  + '③ 独占掲載期間は、PAPのウェブサイトに作品が掲載された日から無期限に適用されます。</li>'
  + '<li><strong>第2条(ウェブサイトおよびSNS使用の同意)</strong><br>'
  + '① 提出された作品はPAP公式サイト(pap-magazine.com)に掲載され、掲載前後にPAP公式SNSアカウント(Instagram、Facebook、YouTube等)でプロモーションや紹介の目的で利用されることがあります。<br>'
  + '② PAPはプロモーション目的で画像のクロップ、リサイズ、フィルター適用等の合理的な範囲の編集を行うことがありますが、作品の本質的な内容を損なう変更は行いません。<br>'
  + '③ すべてのSNS投稿では、提出者およびチームメンバーに対する適切なクレジットが表記されます。</li>'
  + '<li><strong>第3条(クレジット情報の正確性および修正手数料)</strong><br>'
  + '① 提出者は、すべてのクレジット情報(チームメンバー名、Instagramハンドル、ブランド名、ルック別衣装クレジット等)が正確で最新であることを保証します。<br>'
  + '② プレミアム会員はエディトリアル1件につき3回まで無料でクレジットを修正できます。それ以外の場合、掲載後に提出者の責任でクレジット情報の修正が必要となったときは、項目ごとに€100の修正手数料が課され、修正作業開始前に支払う必要があります。<br>'
  + '③ サブミッションフォームに入力されていない情報は省略される可能性があり、PAPはこれについて責任を負いません。<br>'
  + '④ クレジット記載時に全角・半角を問わず全大文字(ALL CAPS)は使用しないでください。</li>'
  + '<li><strong>第4条(コンテンツ使用権および収益分配)</strong><br>'
  + '① 提出された作品がPAPデジタルマガジン(ウェブサイト、アプリ等)または印刷物(紙媒体、出版物等)に掲載されて発生するすべての収益(購読料、販売収益、広告収益等)はすべてPAPに帰属し、提出者およびクリエイティブチームはマガジン掲載による収益について別途の報酬を請求できません。<br>'
  + '② マガジン掲載範囲を超える二次加工または派生商業活動(広告キャンペーン、ブランドコラボ、ライセンシング、展示、マーチャンダイズ等)に作品が活用されて収益が発生する場合、当該活動の純利益(総収益から直接費用を差し引いた額)はPAPとクリエイティブチームが50:50で分配します。<br>'
  + '③ クリエイティブチームへの分配金は提出者またはチーム代表者に一括支給され、チーム代表者からメンバーへの分配方法・比率・時期はチーム代表者の裁量に委ねられ、PAPはチーム内部の収益分配には関与せず、これについて責任を負いません。<br>'
  + '④ 二次的商業利用が発生する場合、PAPは事前に書面(メール含む)で提出者に通知します。</li>'
  + '<li><strong>第5条(著作権および知的財産権)</strong><br>'
  + '① 提出された作品の著作権は原著作者に帰属します。ただし提出者は本規約で定められた範囲でPAPに独占的使用権を付与します。<br>'
  + '② 提出者は、提出されたすべてのコンテンツ(写真、映像、テキスト等)に対する正当な権利を保有しており、当該コンテンツが第三者の著作権、肖像権、商標権、その他の知的財産権または人格権を侵害しないことを保証します。<br>'
  + '③ 第三者権利侵害によりPAPに損害が発生した場合、提出者がそのすべての責任を負います。</li>'
  + '<li><strong>第6条(掲載スケジュール)</strong><br>'
  + '① エディトリアルの掲載はサブミッション承認日から最大2〜3週間を要することがあり、具体的な掲載スケジュールはPAPの編集スケジュールに応じて調整されます。</li>'
  + '<li><strong>第7条(ブランド掲載基準およびブランデッドコンテンツ)</strong><br>'
  + '① エディトリアルには最低4つ以上の異なる衣類ブランドが含まれる必要があります。<br>'
  + '② 単一ブランドのみを使用、あるいは特定ブランドのプロモーションを主目的とするエディトリアルは「ブランデッドコンテンツ」として分類されます。<br>'
  + '③ ブランデッドコンテンツには別途の掲載料金が課され、具体的な金額はPAPとの事前協議により決定されます。<br>'
  + '④ ブランド掲載基準の遵守可否はPAP編集チームが判断します。<br>'
  + '⑤ SPA(ファストファッション)ブランド、およびヴィンテージ・古着・リセール店から調達した衣装は、第1項のブランド数に含まれません。該当の可否はPAP編集チームが判断します。</li>'
  + '<li><strong>第8条(掲載後の修正および削除)</strong><br>'
  + '① PAPウェブサイトおよびSNSにエディトリアルが掲載された後、原則として修正、差し替え、削除は認められません。 ただし、クレジット情報の訂正は第3条によります。<br>'
  + '② ただし、(a)法的紛争または裁判所の命令、(b)第三者権利侵害の確認、(c)重大な事実誤認の発見等、重大な事由がある場合はPAPとの協議により対応可能です。<br>'
  + '③ 上記事由による修正・削除のリクエストには別途の処理手数料が発生することがあります。</li>'
  + '<li><strong>第9条(個人情報の収集および利用)</strong><br>'
  + '① PAPはサブミッションの受付・審査・掲載・クレジット表記・連絡のため、提出者およびチームメンバーの個人情報(氏名、メールアドレス、Instagramハンドル、ウェブサイトURL等)を収集・利用します。<br>'
  + '② 収集された個人情報は上記目的以外には利用されず、PAPプライバシーポリシーに従い安全に管理されます。<br>'
  + '③ 提出者はチームメンバーの個人情報を提供する前に当該メンバーの同意を得たことを確認します。<br>'
  + '④ 個人情報に関する問い合わせはcontact@pap-magazine.comまでご連絡ください。</li>'
  + '<li><strong>第10条(免責および責任制限)</strong><br>'
  + '① PAPはサブミッション審査結果に対する異議申し立てを受け付けません。審査基準と結果はPAP編集チームの専門的判断によります。<br>'
  + '② PAPは天災地変、システム障害、ネットワーク障害等の不可抗力事由によるサービス中断やデータ損失について責任を負いません。<br>'
  + '③ 本規約違反により発生した一切の紛争および損害に関する責任は提出者が負います。</li>'
  + '<li><strong>第11条(規約の改訂)</strong><br>'
  + '① PAPは関連法令の変更やサービスポリシーの変更等、合理的な事由がある場合、本規約を改訂することがあります。<br>'
  + '② 改訂された規約はPAPウェブサイトでの告知後7日を経過した時点から効力を発します。<br>'
  + '③ 提出者が改訂された規約に同意しない場合、サブミッションを中止することができます。</li>'
  + '<li><strong>第12条(準拠法および管轄)</strong><br>'
  + '① 本規約の解釈および適用は大韓民国の法律に従います。<br>'
  + '② 本規約に関連して発生するすべての紛争はソウル中央地方裁判所を第一審の専属管轄裁判所とします。</li>';

  // ─── Chinese (zh) ─────────────────────────────────────────────────────
  T.zh = ''
  + '<li><strong>第1条(作品独家发表)</strong><br>'
  + '① 通过本投稿流程提交的编辑作品(以下"作品")将由 PAP Magazine(以下"PAP")独家发表,投稿人不得将同一作品发表或发布在其他杂志、网络媒体、出版物或类似平台。<br>'
  + '② 若经证实作品违反本条规定而发表于其他媒体,PAP 可立即删除该作品,并对投稿人采取限制后续投稿、法律追责等制裁措施。<br>'
  + '③ 独家发表期限自作品在 PAP 官网发布之日起无限期适用。</li>'
  + '<li><strong>第2条(网站及社交媒体使用同意)</strong><br>'
  + '① 投稿作品将发表于 PAP 官方网站(pap-magazine.com),并可于发布前后通过 PAP 官方社交媒体账号(Instagram、Facebook、YouTube 等)用于推广与介绍目的。<br>'
  + '② PAP 可出于推广目的对图像进行合理范围内的编辑(裁剪、调整尺寸、滤镜等),但不会进行损害作品本质内容的变更。<br>'
  + '③ 所有社交媒体贴文中都会对投稿人及团队成员进行恰当署名。</li>'
  + '<li><strong>第3条(名单准确性与更正费用)</strong><br>'
  + '① 投稿人保证所有署名信息(团队成员姓名、Instagram 账号、品牌名称、各造型服装署名等)的准确性与时效性。<br>'
  + '② 高级会员每篇编辑作品可免费更正署名信息最多 3 次。其他情况下,若发表后因投稿人原因需更正署名信息,每项将收取 100 欧元更正费,须在更正工作开始前支付。<br>'
  + '③ 未在投稿表单中填写的信息可能被省略,PAP 对此不承担责任。<br>'
  + '④ 署名撰写时请勿使用全大写(ALL CAPS)。</li>'
  + '<li><strong>第4条(内容使用权与收益分配)</strong><br>'
  + '① 投稿作品于 PAP 数字杂志(网站、App 等)或印刷出版物(纸本杂志、印刷物等)上发表所产生的全部收益(订阅费、销售收益、广告收益等)归 PAP 所有,投稿人及创作团队不得就杂志发表产生的收益要求额外补偿。<br>'
  + '② 若作品用于杂志发表范围之外的二次加工或派生商业活动(广告战役、品牌联名、授权、展览、周边商品等)并产生收益,该活动的净利润(总收入减去直接成本)由 PAP 与创作团队按 50:50 比例分配。<br>'
  + '③ 分配给创作团队的收益将一次性支付给投稿人或团队代表,由团队代表分配给团队成员的方式、比例及时间完全由团队代表自行决定,PAP 不参与团队内部分配,也不承担相关责任。<br>'
  + '④ 如发生二次商业使用,PAP 将事先以书面(含电邮)方式通知投稿人。</li>'
  + '<li><strong>第5条(著作权与知识产权)</strong><br>'
  + '① 投稿作品的著作权归原作者所有。投稿人在本条款规定范围内授予 PAP 独家使用权。<br>'
  + '② 投稿人保证对所有投稿内容(照片、视频、文本等)拥有合法权利,且相关内容不侵犯第三方著作权、肖像权、商标权、其他知识产权或人格权。<br>'
  + '③ 因侵犯第三方权利致 PAP 受损的,投稿人承担全部责任。</li>'
  + '<li><strong>第6条(发表时间表)</strong><br>'
  + '① 编辑作品自投稿获批之日起可能需要最多 2–3 周进行发表,具体发表时间将根据 PAP 编辑日程调整。</li>'
  + '<li><strong>第7条(品牌收录标准与 Branded Content)</strong><br>'
  + '① 编辑作品须包含至少 4 个不同的服装品牌。<br>'
  + '② 仅使用单一品牌或以推广特定品牌为主要目的的编辑作品被归类为"Branded Content"。<br>'
  + '③ Branded Content 须另行缴纳发布费用,具体金额经与 PAP 事先协商确定。<br>'
  + '④ 是否符合品牌收录标准由 PAP 编辑团队判断。<br>'
  + '⑤ SPA(快时尚)品牌以及来自古着、二手或转售店铺的服装,不计入第①款的品牌数量。是否适用由 PAP 编辑团队判断。</li>'
  + '<li><strong>第8条(发表后修改与删除)</strong><br>'
  + '① 编辑作品于 PAP 网站及社交媒体发表后,原则上不允许修改、替换或删除。 但署名信息的更正适用第3条。<br>'
  + '② 以下重大事由可经与 PAP 协商处理:(a)法律纠纷或法院命令,(b)确认的第三方权利侵权,(c)重大事实错误。<br>'
  + '③ 基于上述原因的修改或删除请求可能产生额外处理费用。</li>'
  + '<li><strong>第9条(个人信息的收集与使用)</strong><br>'
  + '① PAP 为投稿接收、审核、发布、署名与联络之目的,收集和使用投稿人及团队成员的个人信息(姓名、电子邮箱、Instagram 账号、网站 URL 等)。<br>'
  + '② 所收集的个人信息不会用于上述目的以外的用途,并将依据 PAP 隐私政策安全管理。<br>'
  + '③ 投稿人确认在提供团队成员个人信息前已取得该成员同意。<br>'
  + '④ 个人信息相关咨询请联系 contact@pap-magazine.com。</li>'
  + '<li><strong>第10条(免责与责任限制)</strong><br>'
  + '① PAP 不受理对投稿审核结果的异议。审核标准与结果由 PAP 编辑团队专业判断。<br>'
  + '② PAP 不对因不可抗力、系统故障、网络错误等导致的服务中断或数据丢失承担责任。<br>'
  + '③ 因违反本条款引发的所有争议及损失由投稿人承担。</li>'
  + '<li><strong>第11条(条款修订)</strong><br>'
  + '① PAP 可在相关法律变动或服务政策变更等合理事由下修订本条款。<br>'
  + '② 修订后的条款自在 PAP 网站公告 7 日后生效。<br>'
  + '③ 投稿人不同意修订条款的,可中止投稿。</li>'
  + '<li><strong>第12条(适用法律与管辖)</strong><br>'
  + '① 本条款的解释与适用以大韩民国法律为准。<br>'
  + '② 与本条款相关的一切争议,以首尔中央地方法院为一审专属管辖法院。</li>';

  // ─── Russian (ru) ─────────────────────────────────────────────────────
  T.ru = ''
  + '<li><strong>Статья 1 (Эксклюзивная публикация Работы)</strong><br>'
  + '① Эдиториал, отправленный через этот процесс submission («Работа»), публикуется исключительно в PAP Magazine («PAP»). Участники не могут публиковать или распространять ту же Работу в других журналах, онлайн-медиа, публикациях или аналогичных платформах.<br>'
  + '② Если подтверждено, что Работа была опубликована в других медиа в нарушение данного положения, PAP может немедленно удалить Работу и применить санкции к участнику, включая ограничения на будущие submissions и юридические действия.<br>'
  + '③ Период эксклюзивной публикации применяется бессрочно с даты размещения Работы на сайте PAP.</li>'
  + '<li><strong>Статья 2 (Согласие на использование на сайте и в соцсетях)</strong><br>'
  + '① Отправленная Работа будет опубликована на официальном сайте PAP (pap-magazine.com) и может использоваться в промо и презентационных целях в официальных соцсетях PAP (Instagram, Facebook, YouTube и т. д.) до и после публикации.<br>'
  + '② PAP может проводить разумные редактирования — обрезка, изменение размера, применение фильтров — в промо-целях, без искажения сути Работы.<br>'
  + '③ Во всех публикациях в соцсетях будут указаны надлежащие credits участнику и членам команды.</li>'
  + '<li><strong>Статья 3 (Точность credits и плата за корректировку)</strong><br>'
  + '① Участник гарантирует, что вся информация о credits (имена участников команды, Instagram-хендлы, названия брендов, look-by-look credits и т. д.) точна и актуальна.<br>'
  + '② Участники Premium могут бесплатно исправлять credits до 3 раз для одного эдиториала. В остальных случаях, если после публикации требуется корректировка по вине участника, взимается плата 100 € за позицию; оплата производится до начала корректировки.<br>'
  + '③ Информация, не введённая в форму submission, может быть пропущена; PAP не несёт за это ответственности.<br>'
  + '④ Не используйте ВСЕ ЗАГЛАВНЫЕ (ALL CAPS) при написании credits.</li>'
  + '<li><strong>Статья 4 (Права использования и распределение дохода)</strong><br>'
  + '① Весь доход от публикации отправленных Работ в цифровом журнале PAP (сайт, приложение и т. д.) или в печатных изданиях — подписка, продажи, рекламный доход — полностью принадлежит PAP. Участник и творческая команда не могут требовать отдельной компенсации за доход, возникающий от публикации журнала.<br>'
  + '② Если Работа используется для вторичной обработки или производных коммерческих активностей вне публикации (рекламные кампании, коллаборации с брендами, лицензирование, выставки, мерч и т. д.), чистая прибыль (выручка минус прямые затраты) делится в соотношении 50:50 между PAP и творческой командой.<br>'
  + '③ Доля команды выплачивается одним платежом участнику или представителю команды. Порядок, пропорции и сроки внутреннего распределения полностью на усмотрении представителя; PAP не участвует во внутреннем распределении и не несёт за это ответственности.<br>'
  + '④ До любого вторичного коммерческого использования PAP уведомит участника письменно (включая email).</li>'
  + '<li><strong>Статья 5 (Авторские права и интеллектуальная собственность)</strong><br>'
  + '① Авторские права на отправленную Работу остаются у оригинального создателя. Участник, однако, предоставляет PAP эксклюзивные права использования в рамках настоящих условий.<br>'
  + '② Участник гарантирует, что обладает законными правами на весь отправленный контент (фото, видео, тексты и т. д.) и что этот контент не нарушает авторские права, права на изображение, товарные знаки и иные права интеллектуальной собственности или личные права третьих лиц.<br>'
  + '③ Участник несёт полную ответственность за ущерб PAP вследствие нарушения прав третьих лиц.</li>'
  + '<li><strong>Статья 6 (График публикации)</strong><br>'
  + '① Публикация эдиториала может занять до 2–3 недель с даты одобрения submission; конкретный график корректируется согласно редакционному плану PAP.</li>'
  + '<li><strong>Статья 7 (Критерии включения брендов и Branded Content)</strong><br>'
  + '① Эдиториалы должны включать как минимум 4 разных бренда одежды.<br>'
  + '② Эдиториалы с одним брендом или имеющие целью продвижение конкретного бренда классифицируются как «Branded Content».<br>'
  + '③ Branded Content облагается дополнительной платой за публикацию, размер которой определяется по предварительному согласованию с PAP.<br>'
  + '④ Соответствие критериям определяет редакционная команда PAP.<br>'
  + '⑤ Бренды быстрой моды (SPA), а также одежда из винтажных, секонд-хенд и ресейл-магазинов не учитываются в количестве брендов по пункту ①. Решение принимает редакция PAP.</li>'
  + '<li><strong>Статья 8 (Изменения и удаление после публикации)</strong><br>'
  + '① После публикации эдиториала на сайте и в соцсетях PAP изменения, замена или удаление, как правило, не допускаются. Однако исправление credits регулируется Статьёй 3.<br>'
  + '② Исключения возможны по согласованию с PAP только в случаях: (a) судебных споров или постановлений суда, (b) подтверждённого нарушения прав третьих лиц, (c) существенных фактических ошибок.<br>'
  + '③ Запросы на изменение или удаление по указанным причинам могут сопровождаться дополнительными сборами за обработку.</li>'
  + '<li><strong>Статья 9 (Сбор и использование персональных данных)</strong><br>'
  + '① PAP собирает и использует персональные данные (имена, email, Instagram-хендлы, URL сайтов и т. д.) участников и членов команды в целях приёма и проверки submissions, публикации, атрибуции credits и связи.<br>'
  + '② Собранные данные не будут использоваться в иных целях и управляются безопасно в соответствии с политикой конфиденциальности PAP.<br>'
  + '③ Участник подтверждает, что получил согласие членов команды перед передачей их персональных данных.<br>'
  + '④ По вопросам, связанным с персональными данными, пишите на contact@pap-magazine.com.</li>'
  + '<li><strong>Статья 10 (Отказ от ответственности)</strong><br>'
  + '① PAP не принимает апелляций по результатам проверки submissions. Критерии и результаты — в профессиональной компетенции редакции PAP.<br>'
  + '② PAP не несёт ответственности за перерывы в обслуживании или потерю данных вследствие форс-мажора, сбоев систем или сетевых ошибок.<br>'
  + '③ Участник несёт ответственность за все споры и убытки, возникшие вследствие нарушения настоящих условий.</li>'
  + '<li><strong>Статья 11 (Изменение условий)</strong><br>'
  + '① PAP может изменять настоящие условия при наличии разумных оснований, таких как изменения законодательства или политики сервиса.<br>'
  + '② Изменённые условия вступают в силу через 7 дней после публикации уведомления на сайте PAP.<br>'
  + '③ Если участник не согласен с изменёнными условиями, он может прекратить submission.</li>'
  + '<li><strong>Статья 12 (Применимое право и юрисдикция)</strong><br>'
  + '① Настоящие условия регулируются законодательством Республики Корея.<br>'
  + '② Все споры, вытекающие из настоящих условий или связанные с ними, подлежат исключительной юрисдикции Центрального районного суда Сеула в качестве суда первой инстанции.</li>';

  window._PAPTerms = T;
})();
