'use strict';
/** 캐스팅 콜 선공개 메일 문구 9개 언어 (2026-10-02). 제목·본문은 캐스팅 콜 자체(번역본)가 들어간다. */
const CC = {
  ko: { subject: '[7일 선공개] 다음 캐스팅 콜: {title}', heading: '연간 프리미엄 회원께 먼저 알립니다', intro: '다음 호에서 찾는 작품입니다. 이 캐스팅 콜은 {publicAt}에 모두에게 공개되고, 연간 프리미엄 회원은 지금 먼저 봅니다.', deadline: '마감: {deadline}', cta: '지금 제출하기', why: '연간 프리미엄 혜택: 캐스팅 콜 7일 선공개 · 유료 서브미션 1회 면제 · 인스타그램 공동작업자 5명 · 게재 인증서' },
  en: { subject: '[7 days early] Next casting call: {title}', heading: 'An early look for Yearly Premium members', intro: 'This is what we are looking for in the next issue. The call goes public on {publicAt}; Yearly Premium members see it now.', deadline: 'Deadline: {deadline}', cta: 'Submit now', why: 'Yearly Premium perks: casting calls 7 days early · one paid submission waived · 5 Instagram collaborators · publication certificate' },
  it: { subject: '[7 giorni in anticipo] Prossimo casting call: {title}', heading: 'Un’anteprima per i membri Premium annuali', intro: 'Ecco cosa cerchiamo per il prossimo numero. Il casting call sarà pubblico il {publicAt}; i membri Premium annuali lo vedono ora.', deadline: 'Scadenza: {deadline}', cta: 'Invia ora', why: 'Vantaggi Premium annuale: casting call 7 giorni prima · una submission a pagamento esonerata · 5 collaboratori Instagram · certificato di pubblicazione' },
  fr: { subject: '[7 jours d’avance] Prochain casting call : {title}', heading: 'En avant-première pour les membres Premium annuels', intro: 'Voici ce que nous cherchons pour le prochain numéro. L’appel sera public le {publicAt} ; les membres Premium annuels le voient dès maintenant.', deadline: 'Date limite : {deadline}', cta: 'Soumettre maintenant', why: 'Avantages Premium annuel : casting calls 7 jours en avance · une soumission payante offerte · 5 collaborateurs Instagram · certificat de publication' },
  es: { subject: '[7 días antes] Próximo casting call: {title}', heading: 'Un adelanto para miembros Premium anual', intro: 'Esto es lo que buscamos para el próximo número. La convocatoria será pública el {publicAt}; los miembros Premium anual la ven ahora.', deadline: 'Fecha límite: {deadline}', cta: 'Enviar ahora', why: 'Ventajas Premium anual: casting calls 7 días antes · un envío de pago exento · 5 colaboradores de Instagram · certificado de publicación' },
  ja: { subject: '[7日先行] 次のキャスティングコール: {title}', heading: '年間プレミアム会員へ先行案内', intro: '次号で探している作品です。このキャスティングコールは {publicAt} に全員へ公開されます。年間プレミアム会員は今すぐご覧いただけます。', deadline: '締切: {deadline}', cta: '今すぐ提出', why: '年間プレミアム特典: キャスティングコール7日先行 · 有料サブミッション1回免除 · Instagramコラボレーター5名 · 掲載証明書' },
  zh: { subject: '[提前7天] 下一期征稿: {title}', heading: '年度高级会员抢先看', intro: '这是下一期我们在寻找的作品。此征稿将于 {publicAt} 向所有人公开，年度高级会员现在即可查看。', deadline: '截止: {deadline}', cta: '立即投稿', why: '年度高级会员权益: 征稿提前7天 · 免除一次付费投稿 · 5位Instagram合作者 · 刊登证书' },
  ru: { subject: '[На 7 дней раньше] Следующий кастинг-колл: {title}', heading: 'Ранний доступ для годовых Premium-подписчиков', intro: 'Вот что мы ищем для следующего выпуска. Кастинг-колл станет публичным {publicAt}; годовые Premium-подписчики видят его уже сейчас.', deadline: 'Дедлайн: {deadline}', cta: 'Подать сейчас', why: 'Преимущества годового Premium: кастинг-коллы на 7 дней раньше · одна платная подача бесплатно · 5 соавторов в Instagram · сертификат публикации' },
  de: { subject: '[7 Tage früher] Nächster Casting Call: {title}', heading: 'Vorab für Jahres-Premium-Mitglieder', intro: 'Das suchen wir für die nächste Ausgabe. Der Call wird am {publicAt} öffentlich; Jahres-Premium-Mitglieder sehen ihn jetzt schon.', deadline: 'Deadline: {deadline}', cta: 'Jetzt einreichen', why: 'Jahres-Premium-Vorteile: Casting Calls 7 Tage früher · eine kostenpflichtige Einreichung erlassen · 5 Instagram-Mitwirkende · Veröffentlichungszertifikat' },
};
module.exports = { CC };
