'use strict';
/**
 * ISO 3166-1 alpha-2 국가 목록 (2026-09-12) — 크리에이터 자동 매치용 프로필 국가.
 * 도메니코: "나라 및 국가를 쓰는 이유는 나중에 커뮤니티에서 크리에이터들 자동매치 기능을 위해서"
 * 자유 텍스트(Italy/Italia/이탈리아)는 매치가 안 되므로 코드로 저장한다. 화면 표시 이름은
 * 브라우저 Intl.DisplayNames(9개 언어)가 만들고, 영어 이름은 폴백·서버 표시용.
 * frontend/pap-countries.js 의 코드 목록과 반드시 같아야 한다(tests/profile-location.test.js 가 대조).
 */
const COUNTRIES = [
  ['AD', "Andorra"],
  ['AE', "United Arab Emirates"],
  ['AF', "Afghanistan"],
  ['AG', "Antigua & Barbuda"],
  ['AI', "Anguilla"],
  ['AL', "Albania"],
  ['AM', "Armenia"],
  ['AO', "Angola"],
  ['AQ', "Antarctica"],
  ['AR', "Argentina"],
  ['AS', "American Samoa"],
  ['AT', "Austria"],
  ['AU', "Australia"],
  ['AW', "Aruba"],
  ['AX', "Åland Islands"],
  ['AZ', "Azerbaijan"],
  ['BA', "Bosnia & Herzegovina"],
  ['BB', "Barbados"],
  ['BD', "Bangladesh"],
  ['BE', "Belgium"],
  ['BF', "Burkina Faso"],
  ['BG', "Bulgaria"],
  ['BH', "Bahrain"],
  ['BI', "Burundi"],
  ['BJ', "Benin"],
  ['BL', "St. Barthélemy"],
  ['BM', "Bermuda"],
  ['BN', "Brunei"],
  ['BO', "Bolivia"],
  ['BQ', "Caribbean Netherlands"],
  ['BR', "Brazil"],
  ['BS', "Bahamas"],
  ['BT', "Bhutan"],
  ['BV', "Bouvet Island"],
  ['BW', "Botswana"],
  ['BY', "Belarus"],
  ['BZ', "Belize"],
  ['CA', "Canada"],
  ['CC', "Cocos (Keeling) Islands"],
  ['CD', "Congo - Kinshasa"],
  ['CF', "Central African Republic"],
  ['CG', "Congo - Brazzaville"],
  ['CH', "Switzerland"],
  ['CI', "Côte d’Ivoire"],
  ['CK', "Cook Islands"],
  ['CL', "Chile"],
  ['CM', "Cameroon"],
  ['CN', "China"],
  ['CO', "Colombia"],
  ['CR', "Costa Rica"],
  ['CU', "Cuba"],
  ['CV', "Cape Verde"],
  ['CW', "Curaçao"],
  ['CX', "Christmas Island"],
  ['CY', "Cyprus"],
  ['CZ', "Czechia"],
  ['DE', "Germany"],
  ['DJ', "Djibouti"],
  ['DK', "Denmark"],
  ['DM', "Dominica"],
  ['DO', "Dominican Republic"],
  ['DZ', "Algeria"],
  ['EC', "Ecuador"],
  ['EE', "Estonia"],
  ['EG', "Egypt"],
  ['EH', "Western Sahara"],
  ['ER', "Eritrea"],
  ['ES', "Spain"],
  ['ET', "Ethiopia"],
  ['FI', "Finland"],
  ['FJ', "Fiji"],
  ['FK', "Falkland Islands"],
  ['FM', "Micronesia"],
  ['FO', "Faroe Islands"],
  ['FR', "France"],
  ['GA', "Gabon"],
  ['GB', "United Kingdom"],
  ['GD', "Grenada"],
  ['GE', "Georgia"],
  ['GF', "French Guiana"],
  ['GG', "Guernsey"],
  ['GH', "Ghana"],
  ['GI', "Gibraltar"],
  ['GL', "Greenland"],
  ['GM', "Gambia"],
  ['GN', "Guinea"],
  ['GP', "Guadeloupe"],
  ['GQ', "Equatorial Guinea"],
  ['GR', "Greece"],
  ['GS', "South Georgia & South Sandwich Islands"],
  ['GT', "Guatemala"],
  ['GU', "Guam"],
  ['GW', "Guinea-Bissau"],
  ['GY', "Guyana"],
  ['HK', "Hong Kong SAR China"],
  ['HM', "Heard & McDonald Islands"],
  ['HN', "Honduras"],
  ['HR', "Croatia"],
  ['HT', "Haiti"],
  ['HU', "Hungary"],
  ['ID', "Indonesia"],
  ['IE', "Ireland"],
  ['IL', "Israel"],
  ['IM', "Isle of Man"],
  ['IN', "India"],
  ['IO', "British Indian Ocean Territory"],
  ['IQ', "Iraq"],
  ['IR', "Iran"],
  ['IS', "Iceland"],
  ['IT', "Italy"],
  ['JE', "Jersey"],
  ['JM', "Jamaica"],
  ['JO', "Jordan"],
  ['JP', "Japan"],
  ['KE', "Kenya"],
  ['KG', "Kyrgyzstan"],
  ['KH', "Cambodia"],
  ['KI', "Kiribati"],
  ['KM', "Comoros"],
  ['KN', "St. Kitts & Nevis"],
  ['KP', "North Korea"],
  ['KR', "South Korea"],
  ['KW', "Kuwait"],
  ['KY', "Cayman Islands"],
  ['KZ', "Kazakhstan"],
  ['LA', "Laos"],
  ['LB', "Lebanon"],
  ['LC', "St. Lucia"],
  ['LI', "Liechtenstein"],
  ['LK', "Sri Lanka"],
  ['LR', "Liberia"],
  ['LS', "Lesotho"],
  ['LT', "Lithuania"],
  ['LU', "Luxembourg"],
  ['LV', "Latvia"],
  ['LY', "Libya"],
  ['MA', "Morocco"],
  ['MC', "Monaco"],
  ['MD', "Moldova"],
  ['ME', "Montenegro"],
  ['MF', "St. Martin"],
  ['MG', "Madagascar"],
  ['MH', "Marshall Islands"],
  ['MK', "North Macedonia"],
  ['ML', "Mali"],
  ['MM', "Myanmar (Burma)"],
  ['MN', "Mongolia"],
  ['MO', "Macao SAR China"],
  ['MP', "Northern Mariana Islands"],
  ['MQ', "Martinique"],
  ['MR', "Mauritania"],
  ['MS', "Montserrat"],
  ['MT', "Malta"],
  ['MU', "Mauritius"],
  ['MV', "Maldives"],
  ['MW', "Malawi"],
  ['MX', "Mexico"],
  ['MY', "Malaysia"],
  ['MZ', "Mozambique"],
  ['NA', "Namibia"],
  ['NC', "New Caledonia"],
  ['NE', "Niger"],
  ['NF', "Norfolk Island"],
  ['NG', "Nigeria"],
  ['NI', "Nicaragua"],
  ['NL', "Netherlands"],
  ['NO', "Norway"],
  ['NP', "Nepal"],
  ['NR', "Nauru"],
  ['NU', "Niue"],
  ['NZ', "New Zealand"],
  ['OM', "Oman"],
  ['PA', "Panama"],
  ['PE', "Peru"],
  ['PF', "French Polynesia"],
  ['PG', "Papua New Guinea"],
  ['PH', "Philippines"],
  ['PK', "Pakistan"],
  ['PL', "Poland"],
  ['PM', "St. Pierre & Miquelon"],
  ['PN', "Pitcairn Islands"],
  ['PR', "Puerto Rico"],
  ['PS', "Palestinian Territories"],
  ['PT', "Portugal"],
  ['PW', "Palau"],
  ['PY', "Paraguay"],
  ['QA', "Qatar"],
  ['RE', "Réunion"],
  ['RO', "Romania"],
  ['RS', "Serbia"],
  ['RU', "Russia"],
  ['RW', "Rwanda"],
  ['SA', "Saudi Arabia"],
  ['SB', "Solomon Islands"],
  ['SC', "Seychelles"],
  ['SD', "Sudan"],
  ['SE', "Sweden"],
  ['SG', "Singapore"],
  ['SH', "St. Helena"],
  ['SI', "Slovenia"],
  ['SJ', "Svalbard & Jan Mayen"],
  ['SK', "Slovakia"],
  ['SL', "Sierra Leone"],
  ['SM', "San Marino"],
  ['SN', "Senegal"],
  ['SO', "Somalia"],
  ['SR', "Suriname"],
  ['SS', "South Sudan"],
  ['ST', "São Tomé & Príncipe"],
  ['SV', "El Salvador"],
  ['SX', "Sint Maarten"],
  ['SY', "Syria"],
  ['SZ', "Eswatini"],
  ['TC', "Turks & Caicos Islands"],
  ['TD', "Chad"],
  ['TF', "French Southern Territories"],
  ['TG', "Togo"],
  ['TH', "Thailand"],
  ['TJ', "Tajikistan"],
  ['TK', "Tokelau"],
  ['TL', "Timor-Leste"],
  ['TM', "Turkmenistan"],
  ['TN', "Tunisia"],
  ['TO', "Tonga"],
  ['TR', "Türkiye"],
  ['TT', "Trinidad & Tobago"],
  ['TV', "Tuvalu"],
  ['TW', "Taiwan"],
  ['TZ', "Tanzania"],
  ['UA', "Ukraine"],
  ['UG', "Uganda"],
  ['UM', "U.S. Outlying Islands"],
  ['US', "United States"],
  ['UY', "Uruguay"],
  ['UZ', "Uzbekistan"],
  ['VA', "Vatican City"],
  ['VC', "St. Vincent & Grenadines"],
  ['VE', "Venezuela"],
  ['VG', "British Virgin Islands"],
  ['VI', "U.S. Virgin Islands"],
  ['VN', "Vietnam"],
  ['VU', "Vanuatu"],
  ['WF', "Wallis & Futuna"],
  ['WS', "Samoa"],
  ['YE', "Yemen"],
  ['YT', "Mayotte"],
  ['ZA', "South Africa"],
  ['ZM', "Zambia"],
  ['ZW', "Zimbabwe"],
];
const CODE_SET = new Set(COUNTRIES.map((c) => c[0]));
const NAME_BY_CODE = Object.fromEntries(COUNTRIES);
/** 입력(코드 또는 영어 이름)을 코드로. 모르면 ''. */
function normalizeCountryCode(raw) {
  const s = String(raw == null ? '' : raw).trim();
  if (!s) return '';
  const up = s.toUpperCase();
  if (CODE_SET.has(up)) return up;
  const hit = COUNTRIES.find((c) => c[1].toLowerCase() === s.toLowerCase());
  return hit ? hit[0] : '';
}
/** 도시: 공백 정리 + 단어 첫 글자 대문자(라틴). 매치 비교는 lower() 로 한다. */
function normalizeCity(raw) {
  const s = String(raw == null ? '' : raw).replace(/[\u0000-\u001f\u007f]/g, '').replace(/\s+/g, ' ').trim().slice(0, 80);
  return s.replace(/(^|[\s\-'])([a-z])/g, (m, p, ch) => p + ch.toUpperCase());
}
function countryName(code) { return NAME_BY_CODE[String(code || '').toUpperCase()] || ''; }
module.exports = { COUNTRIES, CODE_SET, normalizeCountryCode, normalizeCity, countryName };
