/**
 * 크리에이터 메일 문구 — api/_lib/creatorMailCopy.js (2026-09-24)
 *
 * 도메니코 "세 조각 설정해줘" ②·③ 의 9개 언어 문구만 담는다(데이터 파일).
 *   REPORT  — 게재 2~3주 뒤 한 번 가는 화보 성적표 (templates.creatorReportCard)
 *   MONTHLY — 월간 크리에이터 소식 캠페인 (templates.creatorMonthly)
 *
 * 약속은 실제로 있는 것만 적는다: 풀레터는 프리미엄 월 1건(api/pullletters/index.js 가
 * 서버에서 막는다). 없는 혜택을 쓰면 tests/creator-mail.test.js 가 막는다.
 * 자리표시자: {name} {title} {days} {date} {month} {n} {reach}
 */
'use strict';

const REPORT = {
  ko: {
    subject: '"{title}" 게재 {days}일 성적표',
    heading: '화보 성적표',
    greet: '{name}님, 안녕하세요.',
    greetFallback: '크리에이터',
    intro: 'PAP에 실린 {title}이(가) 지금까지 이렇게 읽혔습니다.',
    reach: '인스타그램 도달', likes: '좋아요', saved: '저장', shares: '공유', web: '웹사이트 조회',
    asOf: '{date} 기준 숫자입니다. 도달은 게시물을 본 인스타그램 계정 수입니다.',
    view: '화보 보기 →',
    next: '다음 화보도 기다리고 있습니다. 촬영에 브랜드 의상이 필요하면 PAP 명의의 공식 풀레터로 쇼룸에 대여를 요청할 수 있습니다(프리미엄 회원, 월 1건).',
    cta: '다음 화보 보내기',
    plCta: '풀레터 알아보기 →',
    footer: 'PAP에 게재된 작품에 대한 안내 메일입니다. 문의는 이 메일에 회신해 주세요.',
  },
  en: {
    subject: '"{title}": your {days}-day report',
    heading: 'Your Editorial Report',
    greet: 'Hi {name},',
    greetFallback: 'there',
    intro: 'Here is how {title} has been seen since it went live on PAP.',
    reach: 'Instagram reach', likes: 'Likes', saved: 'Saves', shares: 'Shares', web: 'Website views',
    asOf: 'Figures as of {date}. Reach is the number of Instagram accounts that saw the post.',
    view: 'View the editorial →',
    next: 'We would love to see your next editorial. If you need brand pieces for the shoot, an official PAP Pull-Letter lets you request loans from showrooms (Premium members, 1 per month).',
    cta: 'SUBMIT YOUR NEXT EDITORIAL',
    plCta: 'About Pull-Letters →',
    footer: 'You are receiving this because your work was published on PAP. Questions? Just reply to this email.',
  },
  it: {
    subject: '"{title}": il report dei primi {days} giorni',
    heading: 'Il report del tuo editoriale',
    greet: 'Ciao {name},',
    greetFallback: '',
    intro: 'Ecco come è stato visto {title} da quando è uscito su PAP.',
    reach: 'Copertura Instagram', likes: 'Mi piace', saved: 'Salvataggi', shares: 'Condivisioni', web: 'Visite al sito',
    asOf: 'Dati aggiornati al {date}. La copertura è il numero di account Instagram che hanno visto il post.',
    view: 'Vedi l’editoriale →',
    next: 'Aspettiamo il tuo prossimo editoriale. Se per lo shooting ti servono capi di brand, con una Pull-Letter ufficiale PAP puoi richiederli in prestito agli showroom (membri Premium, 1 al mese).',
    cta: 'INVIA IL PROSSIMO EDITORIALE',
    plCta: 'Scopri la Pull-Letter →',
    footer: 'Ricevi questa email perché il tuo lavoro è stato pubblicato su PAP. Per domande rispondi a questa email.',
  },
  fr: {
    subject: '« {title} » : votre bilan à {days} jours',
    heading: 'Le bilan de votre éditorial',
    greet: 'Bonjour {name},',
    greetFallback: '',
    intro: 'Voici comment {title} a été vu depuis sa publication sur PAP.',
    reach: 'Couverture Instagram', likes: 'J’aime', saved: 'Enregistrements', shares: 'Partages', web: 'Vues sur le site',
    asOf: 'Chiffres au {date}. La couverture est le nombre de comptes Instagram qui ont vu la publication.',
    view: 'Voir l’éditorial →',
    next: 'Nous attendons votre prochain éditorial. Si vous avez besoin de pièces de marque pour le shooting, une Pull-Letter officielle PAP vous permet d’en demander le prêt aux showrooms (membres Premium, 1 par mois).',
    cta: 'ENVOYER VOTRE PROCHAIN ÉDITORIAL',
    plCta: 'Découvrir la Pull-Letter →',
    footer: 'Vous recevez cet e-mail car votre travail a été publié sur PAP. Une question ? Répondez simplement à cet e-mail.',
  },
  es: {
    subject: '"{title}": tu informe de {days} días',
    heading: 'El informe de tu editorial',
    greet: 'Hola {name}:',
    greetFallback: '',
    intro: 'Así se ha visto {title} desde que se publicó en PAP.',
    reach: 'Alcance en Instagram', likes: 'Me gusta', saved: 'Guardados', shares: 'Compartidos', web: 'Visitas en la web',
    asOf: 'Cifras al {date}. El alcance es el número de cuentas de Instagram que vieron la publicación.',
    view: 'Ver el editorial →',
    next: 'Esperamos tu próximo editorial. Si necesitas prendas de marca para la sesión, con una Pull-Letter oficial de PAP puedes solicitar préstamos a los showrooms (miembros Premium, 1 al mes).',
    cta: 'ENVÍA TU PRÓXIMO EDITORIAL',
    plCta: 'Conoce la Pull-Letter →',
    footer: 'Recibes este correo porque tu trabajo se publicó en PAP. ¿Dudas? Responde a este correo.',
  },
  ja: {
    subject: '「{title}」掲載{days}日レポート',
    heading: 'エディトリアル・レポート',
    greet: '{name}様',
    greetFallback: 'クリエイター',
    intro: 'PAPに掲載された{title}は、これまでにこれだけ見られています。',
    reach: 'Instagramリーチ', likes: 'いいね', saved: '保存', shares: 'シェア', web: 'ウェブサイト閲覧',
    asOf: '{date}時点の数字です。リーチは投稿を見たInstagramアカウントの数です。',
    view: 'エディトリアルを見る →',
    next: '次のエディトリアルもお待ちしています。撮影でブランドの衣装が必要な場合は、PAP名義の公式Pull-Letterでショールームに貸し出しを依頼できます（プレミアム会員・月1件）。',
    cta: '次のエディトリアルを送る',
    plCta: 'Pull-Letterについて →',
    footer: 'PAPに掲載された作品についてのご案内です。ご質問はこのメールにご返信ください。',
  },
  zh: {
    subject: '《{title}》发布{days}天成绩单',
    heading: '大片成绩单',
    greet: '{name}，你好。',
    greetFallback: '创作者',
    intro: '刊登在PAP上的{title}，到目前为止的表现如下。',
    reach: 'Instagram覆盖', likes: '点赞', saved: '收藏', shares: '分享', web: '网站浏览',
    asOf: '数据截至{date}。覆盖是看到这条帖子的Instagram账号数。',
    view: '查看大片 →',
    next: '期待你的下一组大片。如果拍摄需要品牌服装，可以用PAP名义的官方Pull-Letter向展厅申请借衣（高级会员，每月1份）。',
    cta: '投递下一组大片',
    plCta: '了解Pull-Letter →',
    footer: '这是关于你在PAP刊登作品的通知邮件。如有疑问，请直接回复此邮件。',
  },
  ru: {
    subject: '«{title}»: отчёт за {days} дн.',
    heading: 'Отчёт по эдиториалу',
    greet: 'Здравствуйте, {name}!',
    greetFallback: '',
    intro: 'Вот как видели {title} с момента публикации в PAP.',
    reach: 'Охват в Instagram', likes: 'Лайки', saved: 'Сохранения', shares: 'Репосты', web: 'Просмотры на сайте',
    asOf: 'Данные на {date}. Охват: число аккаунтов Instagram, увидевших публикацию.',
    view: 'Открыть эдиториал →',
    next: 'Ждём ваш следующий эдиториал. Если для съёмки нужны вещи брендов, официальное письмо PAP (Pull-Letter) поможет запросить их в шоуруме (участники Premium, 1 в месяц).',
    cta: 'ОТПРАВИТЬ СЛЕДУЮЩИЙ ЭДИТОРИАЛ',
    plCta: 'Подробнее о Pull-Letter →',
    footer: 'Это письмо о вашей работе, опубликованной в PAP. Вопросы? Просто ответьте на это письмо.',
  },
  de: {
    subject: '„{title}“: Ihr Bericht nach {days} Tagen',
    heading: 'Ihr Editorial-Bericht',
    greet: 'Hallo {name},',
    greetFallback: '',
    intro: 'So wurde {title} gesehen, seit es auf PAP erschienen ist.',
    reach: 'Instagram-Reichweite', likes: 'Likes', saved: 'Gespeichert', shares: 'Geteilt', web: 'Website-Aufrufe',
    asOf: 'Stand {date}. Reichweite ist die Zahl der Instagram-Konten, die den Beitrag gesehen haben.',
    view: 'Editorial ansehen →',
    next: 'Wir freuen uns auf Ihr nächstes Editorial. Wenn Sie für das Shooting Markenteile brauchen, können Sie mit einem offiziellen PAP Pull-Letter Leihgaben bei Showrooms anfragen (Premium-Mitglieder, 1 pro Monat).',
    cta: 'NÄCHSTES EDITORIAL EINREICHEN',
    plCta: 'Mehr zum Pull-Letter →',
    footer: 'Sie erhalten diese E-Mail, weil Ihre Arbeit auf PAP veröffentlicht wurde. Fragen? Antworten Sie einfach auf diese E-Mail.',
  },
};

/* 2026-09-25 — 머리글(kicker)·제목도 받는 사람 언어로 (도메니코 "각자의 언어로"). 전에는 9개 언어 모두 FOR CREATIVE TEAMS, 5개 언어 제목이 Creator News. */
const MONTHLY = {
  ko: {
    subject: 'PAP 크리에이터 소식 · {month}',
    preheader: '{month} PAP에 실린 크리에이터 화보와 다음 촬영 안내',
    kicker: '크리에이티브 팀을 위해',
    headline: '{month} 크리에이터 소식',
    stats: '{month} PAP에는 크리에이터 화보 {n}편이 실렸고, 인스타그램에서 모두 합쳐 {reach}개 계정에 닿았습니다.',
    statsEmpty: '{month}에도 PAP는 새로운 크리에이터 화보를 기다렸습니다.',
    featured: '이달 가장 멀리 간 화보',
    reachLabel: '도달',
    theme: '이달의 테마',
    nextTitle: '다음 촬영을 준비하고 계신가요?',
    nextBody: '다음 화보도 PAP로 보내 주세요. 촬영에 브랜드 의상이 필요하면 PAP 명의의 공식 풀레터로 쇼룸에 대여를 요청할 수 있습니다(프리미엄 회원, 월 1건).',
    cta: '화보 보내기',
    plCta: '풀레터 알아보기 →',
  },
  en: {
    subject: 'PAP Creator News · {month}',
    preheader: 'The creator editorials PAP published in {month}, and your next shoot',
    kicker: 'FOR CREATIVE TEAMS',
    headline: 'Creator News · {month}',
    stats: 'In {month}, PAP published {n} creator editorials, reaching {reach} Instagram accounts in total.',
    statsEmpty: 'In {month}, PAP kept its doors open for new creator editorials.',
    featured: 'This month’s farthest-reaching editorials',
    reachLabel: 'Reach',
    theme: 'Theme of the month',
    nextTitle: 'Planning your next shoot?',
    nextBody: 'Send us your next editorial. If you need brand pieces for the shoot, an official PAP Pull-Letter lets you request loans from showrooms (Premium members, 1 per month).',
    cta: 'SUBMIT AN EDITORIAL',
    plCta: 'About Pull-Letters →',
  },
  it: {
    subject: 'PAP Notizie per i creativi · {month}',
    preheader: 'Gli editoriali dei creator pubblicati da PAP a {month} e il tuo prossimo shooting',
    kicker: 'PER I TEAM CREATIVI',
    headline: 'Notizie per i creativi · {month}',
    stats: 'A {month} PAP ha pubblicato {n} editoriali di creator, raggiungendo in totale {reach} account Instagram.',
    statsEmpty: 'Anche a {month} PAP ha aspettato nuovi editoriali dei creator.',
    featured: 'Gli editoriali che sono arrivati più lontano',
    reachLabel: 'Copertura',
    theme: 'Il tema del mese',
    nextTitle: 'Stai preparando il prossimo shooting?',
    nextBody: 'Inviaci il tuo prossimo editoriale. Se per lo shooting ti servono capi di brand, con una Pull-Letter ufficiale PAP puoi richiederli in prestito agli showroom (membri Premium, 1 al mese).',
    cta: 'INVIA UN EDITORIALE',
    plCta: 'Scopri la Pull-Letter →',
  },
  fr: {
    subject: 'PAP Actus créateurs · {month}',
    preheader: 'Les éditoriaux de créateurs publiés par PAP en {month}, et votre prochain shooting',
    kicker: 'POUR LES ÉQUIPES CRÉATIVES',
    headline: 'Actus créateurs · {month}',
    stats: 'En {month}, PAP a publié {n} éditoriaux de créateurs, vus au total par {reach} comptes Instagram.',
    statsEmpty: 'En {month}, PAP a continué d’attendre de nouveaux éditoriaux de créateurs.',
    featured: 'Les éditoriaux qui sont allés le plus loin',
    reachLabel: 'Couverture',
    theme: 'Le thème du mois',
    nextTitle: 'Vous préparez votre prochain shooting ?',
    nextBody: 'Envoyez-nous votre prochain éditorial. Si vous avez besoin de pièces de marque pour le shooting, une Pull-Letter officielle PAP vous permet d’en demander le prêt aux showrooms (membres Premium, 1 par mois).',
    cta: 'ENVOYER UN ÉDITORIAL',
    plCta: 'Découvrir la Pull-Letter →',
  },
  es: {
    subject: 'PAP Noticias para creativos · {month}',
    preheader: 'Los editoriales de creadores que PAP publicó en {month} y tu próxima sesión',
    kicker: 'PARA EQUIPOS CREATIVOS',
    headline: 'Noticias para creativos · {month}',
    stats: 'En {month}, PAP publicó {n} editoriales de creadores, que llegaron en total a {reach} cuentas de Instagram.',
    statsEmpty: 'En {month}, PAP siguió esperando nuevos editoriales de creadores.',
    featured: 'Los editoriales que más lejos llegaron',
    reachLabel: 'Alcance',
    theme: 'El tema del mes',
    nextTitle: '¿Preparas tu próxima sesión?',
    nextBody: 'Envíanos tu próximo editorial. Si necesitas prendas de marca para la sesión, con una Pull-Letter oficial de PAP puedes solicitar préstamos a los showrooms (miembros Premium, 1 al mes).',
    cta: 'ENVÍA UN EDITORIAL',
    plCta: 'Conoce la Pull-Letter →',
  },
  ja: {
    subject: 'PAP クリエイターニュース · {month}',
    preheader: '{month}にPAPへ掲載されたクリエイターのエディトリアルと、次の撮影のご案内',
    kicker: 'クリエイティブチームへ',
    headline: 'クリエイターニュース · {month}',
    stats: '{month}、PAPにはクリエイターのエディトリアルが{n}本掲載され、Instagramで合計{reach}アカウントに届きました。',
    statsEmpty: '{month}も、PAPは新しいクリエイターのエディトリアルをお待ちしていました。',
    featured: '今月いちばん遠くまで届いたエディトリアル',
    reachLabel: 'リーチ',
    theme: '今月のテーマ',
    nextTitle: '次の撮影の準備はできていますか？',
    nextBody: '次のエディトリアルもぜひPAPへお送りください。撮影でブランドの衣装が必要な場合は、PAP名義の公式Pull-Letterでショールームに貸し出しを依頼できます（プレミアム会員・月1件）。',
    cta: 'エディトリアルを送る',
    plCta: 'Pull-Letterについて →',
  },
  zh: {
    subject: 'PAP 创作者月报 · {month}',
    preheader: '{month}刊登在PAP的创作者大片，以及下一次拍摄',
    kicker: '致创意团队',
    headline: '创作者月报 · {month}',
    stats: '{month}，PAP刊登了{n}组创作者大片，在Instagram上合计覆盖{reach}个账号。',
    statsEmpty: '{month}，PAP也一直在等待新的创作者大片。',
    featured: '本月传播最远的大片',
    reachLabel: '覆盖',
    theme: '本月主题',
    nextTitle: '正在筹备下一次拍摄吗？',
    nextBody: '欢迎把你的下一组大片投给PAP。如果拍摄需要品牌服装，可以用PAP名义的官方Pull-Letter向展厅申请借衣（高级会员，每月1份）。',
    cta: '投递大片',
    plCta: '了解Pull-Letter →',
  },
  ru: {
    subject: 'PAP Новости для авторов · {month}',
    preheader: 'Эдиториалы авторов, опубликованные в PAP за {month}, и ваша следующая съёмка',
    kicker: 'ДЛЯ КРЕАТИВНЫХ КОМАНД',
    headline: 'Новости для авторов · {month}',
    stats: 'За {month} PAP опубликовал {n} эдиториалов авторов; вместе они охватили {reach} аккаунтов Instagram.',
    statsEmpty: 'За {month} PAP продолжал ждать новые эдиториалы авторов.',
    featured: 'Эдиториалы месяца с самым большим охватом',
    reachLabel: 'Охват',
    theme: 'Тема месяца',
    nextTitle: 'Готовите следующую съёмку?',
    nextBody: 'Присылайте нам следующий эдиториал. Если для съёмки нужны вещи брендов, официальное письмо PAP (Pull-Letter) поможет запросить их в шоуруме (участники Premium, 1 в месяц).',
    cta: 'ОТПРАВИТЬ ЭДИТОРИАЛ',
    plCta: 'Подробнее о Pull-Letter →',
  },
  de: {
    subject: 'PAP Neuigkeiten für Kreative · {month}',
    preheader: 'Die Creator-Editorials, die PAP im {month} veröffentlicht hat, und Ihr nächstes Shooting',
    kicker: 'FÜR KREATIVTEAMS',
    headline: 'Neuigkeiten für Kreative · {month}',
    stats: 'Im {month} hat PAP {n} Creator-Editorials veröffentlicht, die zusammen {reach} Instagram-Konten erreicht haben.',
    statsEmpty: 'Auch im {month} hat PAP auf neue Creator-Editorials gewartet.',
    featured: 'Die Editorials mit der größten Reichweite',
    reachLabel: 'Reichweite',
    theme: 'Thema des Monats',
    nextTitle: 'Planen Sie Ihr nächstes Shooting?',
    nextBody: 'Senden Sie uns Ihr nächstes Editorial. Wenn Sie für das Shooting Markenteile brauchen, können Sie mit einem offiziellen PAP Pull-Letter Leihgaben bei Showrooms anfragen (Premium-Mitglieder, 1 pro Monat).',
    cta: 'EDITORIAL EINREICHEN',
    plCta: 'Mehr zum Pull-Letter →',
  },
};

const LOCALE_TAG = { ko: 'ko-KR', en: 'en-GB', it: 'it-IT', fr: 'fr-FR', es: 'es-ES', ja: 'ja-JP', zh: 'zh-CN', ru: 'ru-RU', de: 'de-DE' };

module.exports = { REPORT, MONTHLY, LOCALE_TAG };
