'use strict';
/** 화보 공개 알림 메일 문구 9개 언어 (2026-09-25). 설명은 editorialLive.js */
const LIVE = {
  ko: { subject: '"{title}" 화보가 PAP에 공개되었습니다', heading: '화보가 공개되었습니다', body1: '"{title}" 화보가 지금 PAP에 공개되었습니다.', body2: '팀과 팔로워에게 알려 주세요. 아래 링크를 인스타그램 스토리의 링크 스티커나 프로필 링크에 걸면, 팔로워가 전체 컷과 크레딧을 바로 볼 수 있습니다.', cta: '화보 보기', linkLabel: '공유용 링크' },
  en: { subject: '"{title}" is now live on PAP', heading: 'Your editorial is live', body1: '"{title}" is now published on PAP.', body2: 'Let your team and followers know. Add the link below to an Instagram Story link sticker or your bio, and your followers can see every image and the full credits in one tap.', cta: 'View the editorial', linkLabel: 'Link to share' },
  it: { subject: '"{title}" è online su PAP', heading: 'Il tuo editoriale è online', body1: '"{title}" è ora pubblicato su PAP.', body2: 'Fallo sapere al tuo team e ai follower. Aggiungi il link qui sotto a uno sticker link nelle Storie di Instagram o nella bio: i tuoi follower vedranno tutte le immagini e i crediti completi con un tocco.', cta: 'Vedi l’editoriale', linkLabel: 'Link da condividere' },
  fr: { subject: '« {title} » est en ligne sur PAP', heading: 'Votre éditorial est en ligne', body1: '« {title} » est désormais publié sur PAP.', body2: 'Prévenez votre équipe et vos abonnés. Ajoutez le lien ci-dessous à un sticker lien dans vos Stories Instagram ou à votre bio : vos abonnés verront toutes les images et les crédits complets en un geste.', cta: 'Voir l’éditorial', linkLabel: 'Lien à partager' },
  es: { subject: '"{title}" ya está publicado en PAP', heading: 'Tu editorial ya está publicado', body1: '"{title}" ya está publicado en PAP.', body2: 'Cuéntaselo a tu equipo y a tus seguidores. Añade el enlace de abajo a un sticker de enlace en tus Stories de Instagram o a tu bio: tus seguidores verán todas las imágenes y los créditos completos con un toque.', cta: 'Ver el editorial', linkLabel: 'Enlace para compartir' },
  ja: { subject: '「{title}」が PAP で公開されました', heading: 'エディトリアルが公開されました', body1: '「{title}」が PAP で公開されました。', body2: 'チームやフォロワーにお知らせください。下のリンクを Instagram ストーリーズのリンクスタンプやプロフィールに貼ると、フォロワーがすべてのカットとクレジットをすぐに見られます。', cta: 'エディトリアルを見る', linkLabel: 'シェア用リンク' },
  zh: { subject: '《{title}》已在 PAP 上线', heading: '你的大片已上线', body1: '《{title}》现已在 PAP 发布。', body2: '告诉你的团队和粉丝吧。把下面的链接加到 Instagram 快拍的链接贴纸或个人主页,粉丝点一下就能看到全部照片和完整署名。', cta: '查看大片', linkLabel: '分享链接' },
  ru: { subject: '«{title}» опубликован в PAP', heading: 'Ваша съёмка опубликована', body1: '«{title}» теперь опубликован в PAP.', body2: 'Расскажите команде и подписчикам. Добавьте ссылку ниже в стикер-ссылку в Stories Instagram или в описание профиля: подписчики увидят все кадры и полные кредиты в одно касание.', cta: 'Смотреть съёмку', linkLabel: 'Ссылка для публикации' },
  de: { subject: '„{title}“ ist jetzt auf PAP online', heading: 'Dein Editorial ist online', body1: '„{title}“ ist jetzt auf PAP veröffentlicht.', body2: 'Sag deinem Team und deinen Followern Bescheid. Füge den Link unten in einen Link-Sticker deiner Instagram-Story oder in deine Bio ein, dann sehen deine Follower alle Bilder und die kompletten Credits mit einem Tippen.', cta: 'Editorial ansehen', linkLabel: 'Link zum Teilen' },
};
module.exports = { LIVE };
