'use strict';
/**
 * 비회원 뉴스레터 가입 문구 (2026-09-25, 도메니코 "회원가입 없이 이메일만으로 받는 가입창 만들기").
 * 회원 대면 → 9개 언어 필수(.claude/rules/frontend.md 언어 정책). 폴백은 영어.
 *
 * consent 는 가입 화면(frontend/newsletter.html 의 L[lang].consent)과 **글자 하나까지 같아야** 한다.
 * 서버는 이 문구를 newsletter_signups.consent_text 에 남긴다(동의 증명). 테스트가 둘을 비교한다.
 * "광고성 정보 포함"을 명시한다 — 정보통신망법 제50조: 광고성 정보는 사전 동의 대상.
 */
const COPY = {
  ko: {
    consent: '매주 월요일 PAP 뉴스레터(화보·기사·트렌드, 광고성 정보 포함)를 이메일로 받는 데 동의합니다. 언제든 수신 거부할 수 있어요.',
    confirmSubject: 'PAP 뉴스레터 구독을 확인해 주세요',
    confirmHeadline: '버튼 한 번이면 끝나요',
    confirmBody: '아래 버튼을 누르면 매주 월요일 PAP 뉴스레터가 도착해요. 직접 신청하지 않으셨다면 이 메일은 무시하셔도 됩니다.',
    confirmCta: '구독 확인',
    welcomeSubject: 'PAP 뉴스레터 구독이 시작됐어요',
    welcomeHeadline: '환영해요',
    welcomeBody: '매주 월요일 아침, 그 주의 PAP 화보·기사 5편과 트렌드 브리핑 10개를 보내드려요. 첫 호가 오기 전에 이번 주 화보를 먼저 둘러보세요.',
    welcomeCta: '이번 주 화보 보기',
    confirmedTitle: '구독이 확인됐어요',
    confirmedBody: '매주 월요일 아침에 만나요. 환영 메일도 보냈어요.',
    invalidTitle: '링크가 올바르지 않아요',
    invalidBody: '메일에 있는 버튼을 다시 눌러 주세요. 계속 안 되면 다시 구독해 주세요.',
    unsubTitle: '수신 거부가 완료됐어요',
    unsubBody: '더 이상 PAP 뉴스레터를 보내지 않아요. 마음이 바뀌면 언제든 다시 구독할 수 있어요.',
    homeCta: 'PAP 둘러보기',
    resubCta: '다시 구독하기',
    footerNotice: '본 메일은 PAP 뉴스레터를 직접 신청하고 확인하신 분께 발송됩니다.',
    unsubscribe: '수신 거부',
  },
  en: {
    consent: 'I agree to receive the PAP newsletter by email every Monday (editorials, articles and trends, including promotional content). I can unsubscribe at any time.',
    confirmSubject: 'Please confirm your PAP newsletter subscription',
    confirmHeadline: 'One tap and you are in',
    confirmBody: 'Tap the button below and the PAP newsletter will arrive every Monday. If you did not sign up, you can ignore this email.',
    confirmCta: 'Confirm subscription',
    welcomeSubject: 'Your PAP newsletter subscription has started',
    welcomeHeadline: 'Welcome',
    welcomeBody: 'Every Monday morning we will send you five PAP editorials and articles from that week, plus ten trend briefings. Take a look at this week’s editorials before your first issue arrives.',
    welcomeCta: 'See this week’s editorials',
    confirmedTitle: 'Your subscription is confirmed',
    confirmedBody: 'See you every Monday morning. We have also sent you a welcome email.',
    invalidTitle: 'This link is not valid',
    invalidBody: 'Please tap the button in the email again. If it still does not work, subscribe again.',
    unsubTitle: 'You have been unsubscribed',
    unsubBody: 'We will not send you the PAP newsletter anymore. You can subscribe again at any time.',
    homeCta: 'Explore PAP',
    resubCta: 'Subscribe again',
    footerNotice: 'This email is sent to people who signed up for and confirmed the PAP newsletter.',
    unsubscribe: 'Unsubscribe',
  },
  it: {
    consent: 'Accetto di ricevere via email la newsletter PAP ogni lunedì (editoriali, articoli e tendenze, inclusi contenuti promozionali). Posso annullare l’iscrizione in qualsiasi momento.',
    confirmSubject: 'Conferma la tua iscrizione alla newsletter PAP',
    confirmHeadline: 'Basta un tocco',
    confirmBody: 'Tocca il pulsante qui sotto e la newsletter PAP arriverà ogni lunedì. Se non ti sei iscritto tu, puoi ignorare questa email.',
    confirmCta: 'Conferma iscrizione',
    welcomeSubject: 'La tua iscrizione alla newsletter PAP è attiva',
    welcomeHeadline: 'Benvenuto',
    welcomeBody: 'Ogni lunedì mattina ti invieremo cinque editoriali e articoli PAP della settimana e dieci brief sulle tendenze. Dai un’occhiata agli editoriali di questa settimana prima del primo numero.',
    welcomeCta: 'Vedi gli editoriali della settimana',
    confirmedTitle: 'Iscrizione confermata',
    confirmedBody: 'Ci vediamo ogni lunedì mattina. Ti abbiamo inviato anche un’email di benvenuto.',
    invalidTitle: 'Questo link non è valido',
    invalidBody: 'Tocca di nuovo il pulsante nell’email. Se non funziona ancora, iscriviti di nuovo.',
    unsubTitle: 'Iscrizione annullata',
    unsubBody: 'Non ti invieremo più la newsletter PAP. Puoi iscriverti di nuovo in qualsiasi momento.',
    homeCta: 'Esplora PAP',
    resubCta: 'Iscriviti di nuovo',
    footerNotice: 'Questa email è inviata a chi si è iscritto e ha confermato la newsletter PAP.',
    unsubscribe: 'Annulla iscrizione',
  },
  fr: {
    consent: 'J’accepte de recevoir la newsletter PAP par email chaque lundi (éditoriaux, articles et tendances, y compris des contenus promotionnels). Je peux me désabonner à tout moment.',
    confirmSubject: 'Confirmez votre abonnement à la newsletter PAP',
    confirmHeadline: 'Un seul clic suffit',
    confirmBody: 'Touchez le bouton ci-dessous et la newsletter PAP arrivera chaque lundi. Si vous ne vous êtes pas inscrit, ignorez cet email.',
    confirmCta: 'Confirmer l’abonnement',
    welcomeSubject: 'Votre abonnement à la newsletter PAP a commencé',
    welcomeHeadline: 'Bienvenue',
    welcomeBody: 'Chaque lundi matin, nous vous enverrons cinq éditoriaux et articles PAP de la semaine et dix briefs tendances. Découvrez les éditoriaux de cette semaine avant votre premier numéro.',
    welcomeCta: 'Voir les éditoriaux de la semaine',
    confirmedTitle: 'Abonnement confirmé',
    confirmedBody: 'Rendez-vous chaque lundi matin. Nous vous avons aussi envoyé un email de bienvenue.',
    invalidTitle: 'Ce lien n’est pas valide',
    invalidBody: 'Touchez à nouveau le bouton dans l’email. Si cela ne fonctionne toujours pas, abonnez-vous à nouveau.',
    unsubTitle: 'Vous êtes désabonné',
    unsubBody: 'Nous ne vous enverrons plus la newsletter PAP. Vous pouvez vous réabonner à tout moment.',
    homeCta: 'Découvrir PAP',
    resubCta: 'Se réabonner',
    footerNotice: 'Cet email est envoyé aux personnes qui se sont inscrites à la newsletter PAP et l’ont confirmée.',
    unsubscribe: 'Se désabonner',
  },
  es: {
    consent: 'Acepto recibir por email la newsletter de PAP cada lunes (editoriales, artículos y tendencias, incluido contenido promocional). Puedo darme de baja en cualquier momento.',
    confirmSubject: 'Confirma tu suscripción a la newsletter de PAP',
    confirmHeadline: 'Un toque y listo',
    confirmBody: 'Toca el botón de abajo y la newsletter de PAP llegará cada lunes. Si no te suscribiste, puedes ignorar este email.',
    confirmCta: 'Confirmar suscripción',
    welcomeSubject: 'Tu suscripción a la newsletter de PAP ha comenzado',
    welcomeHeadline: 'Bienvenido',
    welcomeBody: 'Cada lunes por la mañana te enviaremos cinco editoriales y artículos de PAP de esa semana y diez briefs de tendencias. Echa un vistazo a los editoriales de esta semana antes de tu primer número.',
    welcomeCta: 'Ver los editoriales de la semana',
    confirmedTitle: 'Suscripción confirmada',
    confirmedBody: 'Nos vemos cada lunes por la mañana. También te enviamos un email de bienvenida.',
    invalidTitle: 'Este enlace no es válido',
    invalidBody: 'Vuelve a tocar el botón del email. Si sigue sin funcionar, suscríbete de nuevo.',
    unsubTitle: 'Te has dado de baja',
    unsubBody: 'Ya no te enviaremos la newsletter de PAP. Puedes volver a suscribirte cuando quieras.',
    homeCta: 'Explorar PAP',
    resubCta: 'Suscribirme de nuevo',
    footerNotice: 'Este email se envía a quienes se suscribieron y confirmaron la newsletter de PAP.',
    unsubscribe: 'Darse de baja',
  },
  ja: {
    consent: '毎週月曜日にPAPニュースレター（エディトリアル・記事・トレンド、広告を含む）をメールで受け取ることに同意します。いつでも配信停止できます。',
    confirmSubject: 'PAPニュースレターの購読を確認してください',
    confirmHeadline: 'ボタンを押すだけで完了',
    confirmBody: '下のボタンを押すと、毎週月曜日にPAPニュースレターが届きます。お申し込みに心当たりがない場合は、このメールを無視してください。',
    confirmCta: '購読を確認',
    welcomeSubject: 'PAPニュースレターの購読が始まりました',
    welcomeHeadline: 'ようこそ',
    welcomeBody: '毎週月曜日の朝、その週のPAPエディトリアル・記事5本とトレンドブリーフィング10本をお届けします。最初の号が届く前に、今週のエディトリアルをご覧ください。',
    welcomeCta: '今週のエディトリアルを見る',
    confirmedTitle: '購読が確認されました',
    confirmedBody: '毎週月曜日の朝にお会いしましょう。ウェルカムメールもお送りしました。',
    invalidTitle: 'このリンクは無効です',
    invalidBody: 'メール内のボタンをもう一度押してください。それでも開けない場合は、もう一度購読してください。',
    unsubTitle: '配信を停止しました',
    unsubBody: 'PAPニュースレターの配信を停止しました。いつでも再購読できます。',
    homeCta: 'PAPを見る',
    resubCta: 'もう一度購読する',
    footerNotice: 'このメールは、PAPニュースレターにご自身で登録し確認された方にお送りしています。',
    unsubscribe: '配信停止',
  },
  zh: {
    consent: '我同意每周一通过邮件接收 PAP 新闻通讯（大片、文章与趋势，含推广信息）。我可以随时退订。',
    confirmSubject: '请确认订阅 PAP 新闻通讯',
    confirmHeadline: '点一下就完成',
    confirmBody: '点击下方按钮，PAP 新闻通讯将在每周一送达。如果不是您本人申请，请忽略此邮件。',
    confirmCta: '确认订阅',
    welcomeSubject: '您的 PAP 新闻通讯订阅已开始',
    welcomeHeadline: '欢迎',
    welcomeBody: '每周一早上，我们会为您送上当周 PAP 大片与文章 5 篇，以及 10 条趋势简报。在第一期送达之前，先看看本周的大片吧。',
    welcomeCta: '查看本周大片',
    confirmedTitle: '订阅已确认',
    confirmedBody: '每周一早上见。我们也给您发送了欢迎邮件。',
    invalidTitle: '此链接无效',
    invalidBody: '请再次点击邮件中的按钮。如果仍然无法打开，请重新订阅。',
    unsubTitle: '已退订',
    unsubBody: '我们将不再向您发送 PAP 新闻通讯。您可以随时重新订阅。',
    homeCta: '浏览 PAP',
    resubCta: '重新订阅',
    footerNotice: '本邮件发送给亲自订阅并确认 PAP 新闻通讯的读者。',
    unsubscribe: '退订',
  },
  ru: {
    consent: 'Я согласен получать рассылку PAP по email каждый понедельник (эдиториалы, статьи и тренды, включая рекламные материалы). Я могу отписаться в любой момент.',
    confirmSubject: 'Подтвердите подписку на рассылку PAP',
    confirmHeadline: 'Одно нажатие, и готово',
    confirmBody: 'Нажмите кнопку ниже, и рассылка PAP будет приходить каждый понедельник. Если вы не подписывались, просто проигнорируйте это письмо.',
    confirmCta: 'Подтвердить подписку',
    welcomeSubject: 'Ваша подписка на рассылку PAP началась',
    welcomeHeadline: 'Добро пожаловать',
    welcomeBody: 'Каждый понедельник утром мы будем присылать пять эдиториалов и статей PAP за неделю и десять трендовых брифингов. Посмотрите эдиториалы этой недели до первого выпуска.',
    welcomeCta: 'Смотреть эдиториалы недели',
    confirmedTitle: 'Подписка подтверждена',
    confirmedBody: 'До встречи в понедельник утром. Мы также отправили вам приветственное письмо.',
    invalidTitle: 'Ссылка недействительна',
    invalidBody: 'Нажмите кнопку в письме ещё раз. Если не получается, подпишитесь заново.',
    unsubTitle: 'Вы отписались',
    unsubBody: 'Мы больше не будем присылать рассылку PAP. Вы можете подписаться снова в любой момент.',
    homeCta: 'Открыть PAP',
    resubCta: 'Подписаться снова',
    footerNotice: 'Это письмо отправлено тем, кто сам подписался на рассылку PAP и подтвердил подписку.',
    unsubscribe: 'Отписаться',
  },
  de: {
    consent: 'Ich willige ein, jeden Montag den PAP-Newsletter per E-Mail zu erhalten (Editorials, Artikel und Trends, einschließlich Werbeinhalten). Ich kann mich jederzeit abmelden.',
    confirmSubject: 'Bitte bestätige dein Abo des PAP-Newsletters',
    confirmHeadline: 'Ein Tipp genügt',
    confirmBody: 'Tippe auf den Button unten, dann kommt der PAP-Newsletter jeden Montag. Wenn du dich nicht angemeldet hast, ignoriere diese E-Mail einfach.',
    confirmCta: 'Abo bestätigen',
    welcomeSubject: 'Dein Abo des PAP-Newsletters hat begonnen',
    welcomeHeadline: 'Willkommen',
    welcomeBody: 'Jeden Montagmorgen schicken wir dir fünf PAP-Editorials und -Artikel der Woche und zehn Trend-Briefings. Schau dir die Editorials dieser Woche an, bevor deine erste Ausgabe kommt.',
    welcomeCta: 'Editorials der Woche ansehen',
    confirmedTitle: 'Abo bestätigt',
    confirmedBody: 'Bis Montagmorgen. Wir haben dir auch eine Willkommens-E-Mail geschickt.',
    invalidTitle: 'Dieser Link ist ungültig',
    invalidBody: 'Tippe noch einmal auf den Button in der E-Mail. Wenn es weiterhin nicht klappt, melde dich erneut an.',
    unsubTitle: 'Du wurdest abgemeldet',
    unsubBody: 'Wir schicken dir den PAP-Newsletter nicht mehr. Du kannst dich jederzeit wieder anmelden.',
    homeCta: 'PAP entdecken',
    resubCta: 'Wieder anmelden',
    footerNotice: 'Diese E-Mail erhalten Personen, die den PAP-Newsletter selbst abonniert und bestätigt haben.',
    unsubscribe: 'Abbestellen',
  },
};
const LANGS = Object.keys(COPY);
function nlCopy(lang) {
  const base = COPY.en;
  const d = COPY[lang] || base;
  return new Proxy(d, { get: (o, k) => (o[k] != null ? o[k] : base[k]) });
}
function normLang(l) {
  const s = String(l || '').toLowerCase().slice(0, 2);
  return COPY[s] ? s : 'en';
}
module.exports = { NEWSLETTER_COPY: COPY, NEWSLETTER_LANGS: LANGS, nlCopy, normLang };
