'use strict';
/** 월간 → 연간 제안 메일 문구 9개 언어 (2026-10-01). 설명은 yearlyOffer.js */
const OFFER = {
  ko: { subject: '연간으로 바꾸면 2개월이 무료입니다', heading: '두 번째 달도 함께해 주셔서 고맙습니다', body1: '월간 프리미엄을 두 달째 이어 주셨습니다. 연간 프리미엄(연 €89.90)은 월간 10개월 값이라 2개월이 무료이고, €380 유료 서브미션이 1년에 1회 면제되며, 화보 인스타그램 게시물에 공동작업자 5명을 직접 지정할 수 있습니다.', body2: '바꾸시려면 아래 버튼으로 연간 프리미엄을 시작해 주세요. 지금 쓰시는 월간 구독은 저희가 자동으로 멈춥니다. 손해를 피하려면 다음 결제일({date}) 직전에 바꾸는 것이 좋습니다. 이 메일은 한 번만 보내드립니다.', cta: '연간 프리미엄 보기' },
  en: { subject: 'Switch to yearly and get two months free', heading: 'Thank you for a second month', body1: 'You have kept monthly Premium for a second month. Yearly Premium (€89.90 a year) costs the same as ten months, so two months are free. It also waives one €380 paid submission a year and lets you choose five Instagram collaborators on your editorial post.', body2: 'To switch, start Yearly Premium with the button below. We stop your current monthly subscription automatically. To avoid losing paid days, switch just before your next billing date ({date}). We send this note only once.', cta: 'See Yearly Premium' },
  it: { subject: 'Passa all’annuale e ottieni due mesi gratis', heading: 'Grazie per il secondo mese', body1: 'Hai mantenuto il Premium mensile per un secondo mese. Il Premium annuale (€89,90 all’anno) costa quanto dieci mesi, quindi due mesi sono gratis. Esonera inoltre un invio a pagamento da €380 all’anno e ti permette di scegliere cinque collaboratori Instagram per il post del tuo editoriale.', body2: 'Per passare, avvia il Premium annuale con il pulsante qui sotto. Fermiamo noi il tuo abbonamento mensile. Per non perdere giorni già pagati, conviene cambiare poco prima della prossima data di addebito ({date}). Inviamo questo messaggio una sola volta.', cta: 'Vedi Premium annuale' },
  fr: { subject: 'Passez à l’annuel : deux mois offerts', heading: 'Merci pour ce deuxième mois', body1: 'Vous avez gardé Premium mensuel un deuxième mois. Premium annuel (€89,90 par an) coûte le prix de dix mois : deux mois sont offerts. Il exonère aussi une soumission payante de €380 par an et vous laisse choisir cinq collaborateurs Instagram pour la publication de votre éditorial.', body2: 'Pour changer, démarrez Premium annuel avec le bouton ci-dessous. Nous arrêtons votre abonnement mensuel automatiquement. Pour ne pas perdre de jours payés, changez juste avant votre prochaine date de prélèvement ({date}). Nous n’envoyons ce message qu’une fois.', cta: 'Voir Premium annuel' },
  es: { subject: 'Pásate al anual y llévate dos meses gratis', heading: 'Gracias por un segundo mes', body1: 'Has mantenido Premium mensual un segundo mes. Premium anual (€89,90 al año) cuesta lo mismo que diez meses, así que dos meses salen gratis. Además exime un envío de pago de €380 al año y te deja elegir cinco colaboradores de Instagram para la publicación de tu editorial.', body2: 'Para cambiar, inicia Premium anual con el botón de abajo. Nosotros detenemos tu suscripción mensual automáticamente. Para no perder días pagados, cambia justo antes de tu próxima fecha de cobro ({date}). Este aviso se envía una sola vez.', cta: 'Ver Premium anual' },
  ja: { subject: '年額に切り替えると2か月分が無料', heading: '2か月目もありがとうございます', body1: '月額プレミアムを2か月目も続けていただきました。年間プレミアム（年€89.90）は月額10か月分の金額なので、2か月分が無料です。さらに€380の有料サブミッションが年1回免除され、エディトリアルのInstagram投稿に共同投稿者を5人まで指定できます。', body2: '切り替えるには、下のボタンから年間プレミアムを開始してください。現在の月額購読は自動で停止します。お支払い済みの日数を無駄にしないため、次回の請求日（{date}）の直前に切り替えるのがおすすめです。このご案内は一度だけお送りします。', cta: '年間プレミアムを見る' },
  zh: { subject: '改为年付，免两个月', heading: '感谢你的第二个月', body1: '你已连续两个月使用月付高级会员。年度高级会员（每年€89.90）只相当于十个月的月费，等于免两个月；每年还免除一次€380付费投稿，并可为作品的Instagram帖子指定5位合作者。', body2: '要切换，请点击下方按钮开始年度高级会员，我们会自动停止你当前的月付订阅。为避免浪费已付天数，建议在下次扣款日（{date}）之前切换。此提醒只发送一次。', cta: '查看年度高级会员' },
  ru: { subject: 'Перейдите на год и получите два месяца бесплатно', heading: 'Спасибо за второй месяц', body1: 'Вы продлили месячный Premium на второй месяц. Годовой Premium (€89,90 в год) стоит как десять месяцев, то есть два месяца бесплатно. Кроме того, одна платная подача за €380 в год не оплачивается, и вы выбираете пять соавторов в Instagram для публикации вашего эдиториала.', body2: 'Чтобы перейти, начните годовой Premium по кнопке ниже. Текущую месячную подписку мы остановим сами. Чтобы не терять оплаченные дни, лучше переходить прямо перед следующей датой списания ({date}). Это письмо приходит один раз.', cta: 'Смотреть годовой Premium' },
  de: { subject: 'Wechseln Sie aufs Jahr und sparen Sie zwei Monate', heading: 'Danke für einen zweiten Monat', body1: 'Sie haben das monatliche Premium einen zweiten Monat behalten. Jahres-Premium (€89,90 im Jahr) kostet so viel wie zehn Monate, zwei Monate sind also gratis. Außerdem entfällt eine kostenpflichtige Einreichung (€380) pro Jahr, und Sie können fünf Instagram-Mitwirkende für den Beitrag Ihres Editorials wählen.', body2: 'Zum Wechseln starten Sie Jahres-Premium über den Button unten. Ihr monatliches Abonnement stoppen wir automatisch. Damit keine bezahlten Tage verloren gehen, wechseln Sie am besten kurz vor dem nächsten Abrechnungsdatum ({date}). Diese Nachricht senden wir nur einmal.', cta: 'Jahres-Premium ansehen' },
};
module.exports = { OFFER };
