#!/usr/bin/env node
/**
 * PAP Magazine — Generate supabase_migrations/021_editorial_brands.sql
 *
 * Two-part migration:
 *   1. CREATE TABLE editorial_brands  (editorial_title, brand_id, role)
 *      — links each editorial to every brand it credits, with the role
 *        that surfaced it (Fashion by / Beauty by / fashion-field).
 *      — PK over all three columns so the same brand can show up under
 *        multiple roles in the same editorial.
 *      — RLS: read for everyone (used by editorial pages + brand pages),
 *        write only for service-role (backfill + admin).
 *   2. INSERT every (editorial_title, brand_id, role) triple harvested
 *      from the production corpus snapshot.
 *
 * editorial_title doubles as the join key:
 *   • DB editorials: matches editorials.title (VARCHAR(500))
 *   • Static snapshot: matches the dict-key title (≤63 chars in current corpus)
 * No FK on editorial_title because the static rows have no DB row to point
 * at. Static→DB migration in a future phase will swap this for an FK.
 *
 * brand_id is FK to brands(brand_id) → all aliases collapse to canonical via
 * brand_aliases (parsed from 018+019+020). ON DELETE CASCADE so removing
 * a brand removes its editorial links.
 *
 * Idempotent: ON CONFLICT DO NOTHING. Re-running on top of admin edits
 * (e.g. brand merges) is safe — existing rows are preserved.
 */

const fs = require('fs');
const path = require('path');
const { aggregate } = require('../api/_lib/brandExtract');

const ROOT = path.resolve(__dirname, '..');
const STATIC_JSON = path.join(ROOT, 'frontend', 'data', 'editorial-details.json');
const SEED_018    = path.join(ROOT, 'supabase_migrations', '018_seed_brands.sql');
const MIG_019     = path.join(ROOT, 'supabase_migrations', '019_brand_aliases_extracted.sql');
const MIG_020     = path.join(ROOT, 'supabase_migrations', '020_brand_aliases_full_corpus.sql');
const OUT_PATH    = path.join(ROOT, 'supabase_migrations', '021_editorial_brands.sql');

// ── Build the alias → brand_id registry (post-018+019+020) ──────────────
function parseAliases(sqlPath) {
  const m = new Map();
  if (!fs.existsSync(sqlPath)) return m;
  const sql = fs.readFileSync(sqlPath, 'utf8');
  const aliasIdx = sql.indexOf('INSERT INTO public.brand_aliases');
  if (aliasIdx < 0) return m;
  const re = /^\s*\('([^']+)'\s*,\s*'([a-z0-9_]+)'\s*,\s*'(?:manual|auto|pending)'\s*\)/gm;
  let match;
  while ((match = re.exec(sql.slice(aliasIdx))) !== null) m.set(match[1], match[2]);
  return m;
}

const aliasToBrandId = new Map([
  ...parseAliases(SEED_018),
  ...parseAliases(MIG_019),
  ...parseAliases(MIG_020),
]);
console.log('Total alias→brand_id mappings (018+019+020): ' + aliasToBrandId.size);

// ── Load corpus + run extractor with link collection ────────────────────
const jr = JSON.parse(fs.readFileSync(STATIC_JSON, 'utf8'));
const editorials = Object.keys(jr).map(title => Object.assign({ title }, jr[title]));

const result = aggregate(editorials, { frequentThreshold: 1, collectLinks: true });
const links = result.editorial_brand_links;
console.log('Raw link tokens: ' + links.length);

// ── Resolve alias → canonical brand_id, dedup by (title, brand_id, role) ──
const seen = new Set();
const rows = [];
let unmapped = 0;

for (const link of links) {
  const brandId = aliasToBrandId.get(link.alias);
  if (!brandId) { unmapped++; continue; }   // can happen for stop-aliases that slipped through
  const key = link.editorial_title + '|' + brandId + '|' + link.role;
  if (seen.has(key)) continue;
  seen.add(key);
  rows.push({ editorial_title: link.editorial_title, brand_id: brandId, role: link.role });
}

console.log('Unmapped aliases (no brand_id): ' + unmapped);
console.log('Deduped link rows: ' + rows.length);

// ── Emit SQL ────────────────────────────────────────────────────────────
function sqlString(s) {
  if (s === null || s === undefined) return 'NULL';
  return "'" + String(s).replace(/'/g, "''") + "'";
}

const lines = [];
lines.push('/**');
lines.push(' * PAP Magazine — Editorial ↔ brand link table + initial backfill');
lines.push(' * Step 21 in supabase_migrations/README.md execution order.');
lines.push(' *');
lines.push(' * Generated by scripts/generate_021_migration.js on ' + new Date().toISOString().slice(0,10) + '.');
lines.push(' *');
lines.push(' * Backfill scope: ' + rows.length + ' (editorial_title, brand_id, role) rows from');
lines.push(' * ' + editorials.length + ' editorials in the production static snapshot.');
lines.push(' *');
lines.push(' * Powers downstream features:');
lines.push(' *   • Editorial pages: "shop the brands featured here" carousel');
lines.push(' *   • Brand pages: "all editorials featuring BALENCIAGA"');
lines.push(' *   • /api/go/[id] click attribution joined back to source editorial');
lines.push(' */');
lines.push('');
lines.push('-- ── Schema ───────────────────────────────────────────────────────────');
lines.push('CREATE TABLE IF NOT EXISTS public.editorial_brands (');
lines.push('  editorial_title  TEXT NOT NULL,');
lines.push('  brand_id         TEXT NOT NULL REFERENCES public.brands(brand_id) ON DELETE CASCADE,');
lines.push('  role             TEXT NOT NULL,');
lines.push('  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),');
lines.push('  PRIMARY KEY (editorial_title, brand_id, role)');
lines.push(');');
lines.push('');
lines.push('CREATE INDEX IF NOT EXISTS editorial_brands_brand_id_idx ON public.editorial_brands(brand_id);');
lines.push('CREATE INDEX IF NOT EXISTS editorial_brands_editorial_title_idx ON public.editorial_brands(editorial_title);');
lines.push('');
lines.push('-- RLS: public read (used by editorial+brand pages), service-role write only');
lines.push('ALTER TABLE public.editorial_brands ENABLE ROW LEVEL SECURITY;');
lines.push('CREATE POLICY editorial_brands_public_read ON public.editorial_brands');
lines.push('  FOR SELECT USING (true);');
lines.push('CREATE POLICY editorial_brands_service_write ON public.editorial_brands');
lines.push('  FOR ALL TO service_role USING (true) WITH CHECK (true);');
lines.push('');
// Sort for stability — easier to diff regenerations
rows.sort((a, b) => {
  if (a.editorial_title !== b.editorial_title) return a.editorial_title.localeCompare(b.editorial_title);
  if (a.brand_id !== b.brand_id) return a.brand_id.localeCompare(b.brand_id);
  return a.role.localeCompare(b.role);
});

// Chunk into BATCH_SIZE-row INSERTs so the Supabase SQL Editor stays responsive
// when pasting and so a malformed row only fails its own batch.
const BATCH_SIZE = 3000;
const batchCount = Math.ceil(rows.length / BATCH_SIZE);
lines.push('-- ── Backfill (' + rows.length + ' rows in ' + batchCount + ' batches of ≤' + BATCH_SIZE + ') ─────────');

for (let bi = 0; bi < batchCount; bi++) {
  const slice = rows.slice(bi * BATCH_SIZE, (bi + 1) * BATCH_SIZE);
  lines.push('-- batch ' + (bi + 1) + '/' + batchCount + '  (rows ' + (bi * BATCH_SIZE + 1) + '..' + (bi * BATCH_SIZE + slice.length) + ')');
  lines.push('INSERT INTO public.editorial_brands (editorial_title, brand_id, role) VALUES');
  const valueRows = slice.map(r => '  (' + sqlString(r.editorial_title) + ', ' + sqlString(r.brand_id) + ', ' + sqlString(r.role) + ')');
  lines.push(valueRows.join(',\n'));
  lines.push('ON CONFLICT (editorial_title, brand_id, role) DO NOTHING;');
  lines.push('');
}

fs.writeFileSync(OUT_PATH, lines.join('\n'));
console.log('\nWrote ' + OUT_PATH);
console.log('  ' + lines.length + ' SQL lines');

// Quick stats
const editorialsWithLinks = new Set(rows.map(r => r.editorial_title));
const brandsLinked = new Set(rows.map(r => r.brand_id));
console.log('\n=== Coverage ===');
console.log('  Editorials with at least one brand link: ' + editorialsWithLinks.size);
console.log('  Distinct brands linked: ' + brandsLinked.size);
console.log('  Avg links per linked editorial: ' + (rows.length / editorialsWithLinks.size).toFixed(1));
